### ISSUE TITLE
Product ecomm_id enclosed in brackets incorrectly in the dataLayer

### ISSUE THREAD

**Issue by accetturo** [duracelltomi/gtm4wp#10]
Product ID with the remarketing tag is being enclosed in brackets, it should not be enclosed in anything for correct matching with Google Merchant Feed

**Comment by duracelltomi** [comment]
It the official documentation there is a bracket for cases where there is more than one ID to report:
https://developers.google.com/adwords-remarketing-tag/parameters#retail
https://support.google.com/adwords/answer/3103357?hl=en
