### ISSUE TITLE
Feature Request: Host JS Locally

### ISSUE THREAD

**Issue by f3bruary** [duracelltomi/gtm4wp#101]
I would like to request the feature to host the javascript files locally instead of having to request them from Google each page load. Kind of like the CAOS plugin does, but just for Analytics.

This way out site speeds could improve significantly. A metric which is getting more important as time passes and even effect SEA quality scores.

Additionally a cron job must be in place to fetch new .js files every now and then in case Google updates those.

This is a low priority request, but I hope you'll consider it.

**Comment by duracelltomi** [comment]
I am not really sure that a site where only gtm.js is loaded from Google's servers should suffer from any performance issue :-)

I have read lots of topics where analytics.js and other files are loaded locally just to improve GMetrix scores but I am not confident that this has meaningful impact on business KPIs

I am not fully against adding this into the plugin but first I would be happy to see some real life case studies where moving gtm.js to a local file improved business results significantly.

Also this will introduce some false positive "bugs": I can see my inbox getting messages from users turning this on and after publishing a new GTM container version they do not see any change in their tracking :-)

**Comment by Paktas** [comment]
This might have partially addressed this on #230 issue with version [v1.17](https://github.com/duracelltomi/gtm4wp/milestone/13)

**Comment by Paktas** [comment]
Also addressed by `GTM4WP_OPTION_GTMCUSTOMPATH` configuration on 055324ad62221c1599077cb0e751524471865d40 commit. Look forward to playing around with it.
