### ISSUE TITLE
i18n issue: string missed at admin/admin.php:732

### ISSUE THREAD

**Issue by huanyichuang** [duracelltomi/gtm4wp#102]
As titled, the string at line 732 in admin/admin.php is not available due to the issue of get_text function.

**Comment by koconder** [comment]
@huanyichuang what version of the plugin, wordpress and PHP are you using? - Also a list of your plugins may help ass 732 in admin/admin.php is related to 3rd party plugin intergrations

**Comment by duracelltomi** [comment]
v1.9.1 will be released very soon, I would say @huanyichuang  you should test this with the that version and if you still see some untranslated string, you should use the line numbers of v1.9.1

**Comment by huanyichuang** [comment]
Thanks for your kind reply, I will check it and tell you if anything is fine

**Comment by duracelltomi** [comment]
@huanyichuang we are nearing the release of v1.10 - does this issue still exists for you?

**Comment by duracelltomi** [comment]
@huanyichuang if we can not hear any reply from you until 25th June, I will need to close this thread without any code change

**Comment by koconder** [comment]
@duracelltomi safe to close
