### ISSUE TITLE
Cannot be detected under Native mode of the WordPress official AMP plugin.

### ISSUE THREAD

**Issue by huanyichuang** [duracelltomi/gtm4wp#108]
System Info:
WordPress v5.0.3
GTM4WP v1.9
AMP v1.0.2

After I installed the [Official AMP Plugin](https://wordpress.org/plugins/amp/), I found that I couldn't detect my GTM container.
I opened the developer tool of my browser and found the script of GTM not embedded. But everything went fine after I switched to Paired mode.
I think the future version be excellent if it integrates this feature of supporting Native mode.

**Comment by koconder** [comment]
Hi @huanyichuang do you mind explaining the native and paired mode. I worked on the initial beta release of the AMP integration and happy to help resolve/improve things there.

**Comment by koconder** [comment]
Also adding to my previous comment, I will be revisiting AMP and FBIA implementations as soon as the latest changes on testing are merged into the current repository version.

**Comment by duracelltomi** [comment]
Sorry everyone for the delay, @koconder 's latest changes have been merged :-)

**Comment by koconder** [comment]
@huanyichuang still need you to explain the query?
@duracelltomi thanks!

**Comment by koconder** [comment]
Related to #125
