### ISSUE TITLE
Question about EEC events

### ISSUE THREAD

**Issue by hamedkian** [duracelltomi/gtm4wp#109]
Hi Thomas,

Thank you so much for the amazing plugin, I would be grateful if you could list all the events pushed into the data layer related to Enhanced e-commerce. 
On the plugin EEC setup page, the following are listed:
gtm4wp.addProductToCartEEC
gtm4wp.productClickEEC
gtm4wp.removeFromCartEEC
gtm4wp.checkoutOptionECC
gtm4wp.changeDetailViewEEC
gtm4wp.productImpressionEEC

Are there any other events?

**Comment by duracelltomi** [comment]
Hi,

Those are all the events related to enhanced ecommerce tracking.

There is also a `gtm4wp.orderCompletedEEC` event on the order received page but this is for legacy reasons, you should not use it if you setup tracking based on the mentioned setup article.

**Comment by hamedkian** [comment]
Thank you for your response. 

My problem is that the transactions show up in the GA but the prices and the revenue don’t.

I set DLV for the prices added to the label of the e-commerce tag to see if they are readable. They are shown in the label of the events but are not shown in the ecommerce section!

**Comment by duracelltomi** [comment]
Could you grab the data layer code from page source on an order received page?

**Comment by hamedkian** [comment]
The following is the data layer code from the source. Please note that I have put ''1" instead of the private information. 

<script data-cfasync="false" type="text/javascript">//<![CDATA[
--
  | dataLayer.push({"visitorLoginState":"logged-in","visitorType":"bbp_keymaster","visitorEmail":"111@111.com","visitorRegistrationDate":1542712807,"visitorUsername":"11111","visitorId":38435,"visitorIP":"111.111.16.6","pageTitle":"1111111 - 11111","pagePostType":"page","pagePostType2":"single-page","pagePostAuthorID":1,"pagePostAuthor":"1111","pagePostDate":"1111","pagePostDateYear":"1111","pagePostDateMonth":"1","pagePostDateDay":"11","postID":59935,"postFormat":"standard","customerTotalOrders":1,"customerTotalOrderValue":"1000.00","customerFirstName":"11","customerLastName":"11","customerBillingFirstName":"11","customerBillingLastName":"11","customerBillingCompany":"","customerBillingAddress1":"33","customerBillingAddress2":"","customerBillingCity":"3770","customerBillingPostcode":"9828188221","customerBillingCountry":"11","customerBillingEmail":"11@gmail.com","customerBillingPhone":"+11111111111","customerShippingFirstName":"","customerShippingLastName":"","customerShippingCompany":"","customerShippingAddress1":"","customerShippingAddress2":"","customerShippingCity":"","customerShippingPostcode":"","customerShippingCountry":"","ecommerce":{"currencyCode":"IRR","purchase":{"actionField":{"id":"83116","affiliation":"","revenue":"1000","tax":"0","shipping":"0","coupon":""},"products":[{"id":60891,"name":"test","sku":"test-moodle","category":"book","price":1000,"currency":"IRR","stocklevel":97,"quantity":1}]}},"event":"gtm4wp.orderCompletedEEC"});//]]>

**Comment by duracelltomi** [comment]
I guess the formatting of the editor has "eaten" most part of your reply :-)

**Comment by hamedkian** [comment]
![image](https://user-images.githubusercontent.com/44964263/52960593-2e8d9b80-33aa-11e9-9cc9-3cd48ed6978a.png)

**Comment by hamedkian** [comment]
let me see if it shows this time, 

`<script data-cfasync="false" type="text/javascript">//<![CDATA[
--
  | dataLayer.push({"visitorLoginState":"logged-in","visitorType":"bbp_keymaster","visitorEmail":"111@111.com","visitorRegistrationDate":1542712807,"visitorUsername":"11111","visitorId":38435,"visitorIP":"111.111.16.6","pageTitle":"1111111 - 11111","pagePostType":"page","pagePostType2":"single-page","pagePostAuthorID":1,"pagePostAuthor":"1111","pagePostDate":"1111","pagePostDateYear":"1111","pagePostDateMonth":"1","pagePostDateDay":"11","postID":59935,"postFormat":"standard","customerTotalOrders":1,"customerTotalOrderValue":"1000.00","customerFirstName":"11","customerLastName":"11","customerBillingFirstName":"11","customerBillingLastName":"11","customerBillingCompany":"","customerBillingAddress1":"33","customerBillingAddress2":"","customerBillingCity":"3770","customerBillingPostcode":"9828188221","customerBillingCountry":"11","customerBillingEmail":"11@gmail.com","customerBillingPhone":"+11111111111","customerShippingFirstName":"","customerShippingLastName":"","customerShippingCompany":"","customerShippingAddress1":"","customerShippingAddress2":"","customerShippingCity":"","customerShippingPostcode":"","customerShippingCountry":"","ecommerce":{"currencyCode":"IRR","purchase":{"actionField":{"id":"83116","affiliation":"","revenue":"1000","tax":"0","shipping":"0","coupon":""},"products":[{"id":60891,"name":"test","sku":"test-moodle","category":"book","price":1000,"currency":"IRR","stocklevel":97,"quantity":1}]}},"event":"gtm4wp.orderCompletedEEC"});//]]>
`

**Comment by duracelltomi** [comment]
The most important part if this one:

```
 "ecommerce": {
        "currencyCode": "IRR",
        "purchase": {
            "actionField": {
                "id": "83116",
                "affiliation": "",
                "revenue": "1000",
                "tax": "0",
                "shipping": "0",
                "coupon": ""
            },
            "products": [{
                "id": 60891,
                "name": "test",
                "sku": "test-moodle",
                "category": "book",
                "price": 1000,
                "currency": "IRR",
                "stocklevel": 97,
                "quantity": 1
            }]
        }
    },

```

That means that the plugin adds the necessary code into the data layer.
You can also see that the revenue and price fields are populated correctly.

What is the value entered into your Data Layer Variable on the GTM UI?

**Comment by hamedkian** [comment]
The values entered into the data layer variables on the GTM debug are the same. 

I think the problem would be with the currencyCode, as IRR is not supported by GA. I might need to change it into USD via customTask.

**Comment by hamedkian** [comment]
I set a field in the GA settings for the currencyCode to USD and the problem is solved. Now I am receiving the revenue and prices. Thanks for your response Thomas.

**Comment by hamedkian** [comment]
I set a field in the GA settings for the currencyCode to USD and the problem is solved. Now I am receiving the revenue and prices. Thanks for your response and help Thomas.

**Comment by duracelltomi** [comment]
You are welcome :-)

**Comment by 6630nokia** [comment]
Hi,
how can i track the coupon code?

**Comment by duracelltomi** [comment]
Coupon codes are part of the purchase entry on the order received page.
You can create a data layer variable on the GTM UI and use this variable name: ecommerce.purchase.actionField.coupon

**Comment by 6630nokia** [comment]
Thank you
