### ISSUE TITLE
Add a new placement option to be able to enter a custom WP hook

### ISSUE THREAD

**Issue by duracelltomi** [duracelltomi/gtm4wp#111]
Original thread:
https://wordpress.org/support/topic/feature-suggestion-specify-after-body-hook/

> I have a suggestion for an alternative way to place the “after body tag” GTM code snippet: Let the user specify the name of a hook.
> 
> There is no official hook for just after the opening body tag in WordPress’ standard themes. (As to why this is, I will never understand …!)
> 
> However, many themes specify their own hooks at this position. For example, WooCommerce’s free Storefront theme inserts an action hook named ‘storefront_before_header’.

**Comment by koconder** [comment]
I think this is a great idea, could also add the hook exists for the major theme frameworks like Divi etc.

**Comment by duracelltomi** [comment]
It would be great if we could also collect the body open hooks of well known themes and add support for that without the need to enter a hook name. But of course a custom hook option will be welcome as well

**Comment by duracelltomi** [comment]
I guess that with the introduction of wp_body_open this feature request is now obsolete
https://github.com/duracelltomi/gtm4wp/issues/116
