### ISSUE TITLE
Undefined variables on load with mod pagespeed defering javascript

### ISSUE THREAD

**Issue by frostbyte3** [duracelltomi/gtm4wp#112]
The plugin adds the gtag script in the head but doesn't account for the users who use Google's mod_pagespeed to defer js, which means the variables used for determining scroll, debug mode etc aren't found on load and therefore throw errors. This is easily fixed by adding a "data-pagespeed-no-defer" attribute to the $_gtm_top_content <script> tag in public/frontend.php, which will let pagespeed (if it's installed) know not to defer this js. I tried to make a PR to include this (as adding the attribute has no effect on sites without pagespeed, but breaks on those with it) but I couldn't push a branch due to 403 error, maybe I did it wrong but if this could be added so users like me don't need to worry about their site breaking if I want to update this plugin that'd be flippin fantastic! Thanks!

**Comment by duracelltomi** [comment]
Thanks for the ticket, I will add this fix into the core soon!
