### ISSUE TITLE
Number field should not be quoted: ‘transactionTotal’

### ISSUE THREAD

**Issue by chammer85** [duracelltomi/gtm4wp#114]
This is my first time using your plugin and when I completed a purchase in WooCommerce my Google Tag Assistant was throwing 3 errors.

Number field should not be quoted: ‘transactionTotal’
Number field should not be quoted: ‘transactionShipping’
Number field should not be quoted: ‘transactionTax’

I put in a ticket on Wordpress (https://wordpress.org/support/topic/number-field-should-not-be-quoted-transactiontotal/) at first but now that I've gone ahead and investigated I feel like this is a bug and I was able to fix it on my end by making those properties Numbers instead of Strings.

**Comment by chammer85** [comment]
`$dataLayer["transactionTotal"] = intval($order_revenue);
if ( $gtm4wp_is_woocommerce3 ) {
   $dataLayer["transactionShipping"] = intval($order->get_shipping_total());
} else {
   $dataLayer["transactionShipping"] = intval($order->get_total_shipping());
}
$dataLayer["transactionTax"] = intval($order->get_total_tax());`

**Comment by chammer85** [comment]
`$dataLayer["transactionTotal"] = intval($order_revenue);`
`if ( $gtm4wp_is_woocommerce3 ) {`
`   $dataLayer["transactionShipping"] = intval($order->get_shipping_total());`
`} else {`
`   $dataLayer["transactionShipping"] = intval($order->get_total_shipping());`
`}`
`$dataLayer["transactionTax"] = intval($order->get_total_tax());`

**Comment by duracelltomi** [comment]
Hi,

Thanks, I have seen this message before but as far as I have seen, tracking is working correctly and all values are stored in GA and other measurement systems.

intval() will however round up decimal values:

`echo intval(4.2); // This will be 4`

Currencies like USD or EUR will have such values which would break proper tracking. Maybe [floatval()](http://php.net/manual/en/function.floatval.php) would be better.

**Comment by chammer85** [comment]
Thanks for pointing out the wrong method used for the integer. Is this something you plan on implementing as a change or what is your stance on this? 

Maybe it has to do with enabling classic and enhanced ecommerce? I noticed that when our plugin was setup both of those were flagged which is the reason those properties existed in the dataLayer in the first place.

Do you have a hook or filter that I could use to modify the returns on those? That would be preferred as I don't like to override core plugin code.

**Comment by chammer85** [comment]
Confirming the error comes from our analytics tag from GTM because we are using enhanced ecommerce but having those properties in the dataLayer it was complaining about them being strings. For now I just removed the classic integration because I am able to get the same data from the enhanced object. I guess it would be worth fixing if someone was trying to run classic and enhanced at the same time but I don't know why anyone would really need both.

**Comment by duracelltomi** [comment]
So far where I have setup classic tracking, all data is present in GA reports but if you say you miss transaction values, I will definitely include a change for this part of the code.
