### ISSUE TITLE
New wp_body_open hook

### ISSUE THREAD

**Issue by duracelltomi** [duracelltomi/gtm4wp#116]
This should be definitely supported to make noscript code integration easier

https://make.wordpress.org/themes/2019/03/29/addition-of-new-wp_body_open-hook/

**Comment by daviedR** [comment]
+1

With this new hook, I think the footer option is no longer beneficial.

**Comment by duracelltomi** [comment]
Just a quick note: I will still use the footer option as a default until WP 5.2 is present on a larger number of sites AND themes start to support this new hook more broadly
