### ISSUE TITLE
Problem with ecommerce datalayer which multiple checkout pages

### ISSUE THREAD

**Issue by asongdon** [duracelltomi/gtm4wp#119]
As far as I understand the plugin will add the ecommerce datalayer on the checkout page that was set from Woocommerce setting. But the problem is that I have two separate pages for the checkout with different payment gateway.

How do we come around this so we can have datalayer on another checkout page?

![Screenshot 2019-05-07 14 32 54](https://user-images.githubusercontent.com/27675606/57299618-4cc78580-70d5-11e9-80f1-1d6b134ad7db.png)

From the screenshot: The datalayer display correctly on /checkout/ but I would like it to display on /klarna-checkout/ as well.

**Comment by koconder** [comment]
@asongdon what plugin/system/theme/method are you using to split the cart into sections and create klarna-checkout?

**Comment by duracelltomi** [comment]
I had tested with Klarna some time ago and it seemed to me working with GTM4WP but I did not follow changes of this plugin and I am not sure how this could be fixed. Klarna alters the default flow of the WooCommerce checkout in many ways, I wonder how other plugins can deal with those changes that does not seem to me supporting standard WP hooks and filters.

**Comment by duracelltomi** [comment]
Closing this thread due to no reply
