### ISSUE TITLE
Possible PHP warning on admin

### ISSUE THREAD

**Issue by duracelltomi** [duracelltomi/gtm4wp#121]
More details:
https://wordpress.org/support/topic/warning-array_merge-10/

> Warning: array_merge(): Argument #2 is not an array in /home/pigzilla/public_html/wp-content/plugins/duracelltomi-google-tag-manager/admin/admin.php on line 1409

The mentioned code is preparing admin notices of possible plugin conflicts.
I might need to add a type check before array_merge

**Comment by koconder** [comment]
Added a PR for this one
