### ISSUE TITLE
Sometimes missing product list data

### ISSUE THREAD

**Issue by Blueboots** [duracelltomi/gtm4wp#122]
Hello Thomas,

on our site there are product pages with suggested additional products at the bottom. Sometimes the ecommerce list and impression data looks fine, and other times nothing is generated. In the latter case, clicking on one of the suggested products does activate  gtm4wp.productClickEEC event.

Here are 2 example pages with the differing behaviours. 
Looks good to me - https://lafargayherranz.com/comprar/cambridge-audio-dacmagic-100/
Not working - https://lafargayherranz.com/comprar/cambridge-audio-dacmagic-xs/

I also notice that the presence of a URL parameter breaks the behaviour for me as well, for example:

Looks good to me - https://lafargayherranz.com/comprar/yamaha-r-s202d/
Not working - https://lafargayherranz.com/comprar/yamaha-r-s202d/?pa_color=negro

Any help would be great as I'm a marketer just getting dug into the coding side of things.

**Comment by duracelltomi** [comment]
Thanks for the report!

I need to close some other threads first but I will look at this soon

**Comment by duracelltomi** [comment]
Sorry @Blueboots  for this late reply.

I checked your site and I identified a bug in the JS code of GTM4WP.
You can bypass this bug currently if you set a number in the "Products per impression" option and setup an additional GA event tag as described in Step 9 here:
https://gtm4wp.com/how-to-articles/how-to-setup-enhanced-ecommerce-tracking
