### ISSUE TITLE
Oxygen Builder Support

### ISSUE THREAD

**Issue by wkoehn** [duracelltomi/gtm4wp#129]
I'd like to request support for the Oxygen builder plugin. This builder disables the entire theme in WordPress which breaks a few things. There is an action available (ct_before_builder) that fires immediately after the opening <body> tag in Oxygen. I'm not very familiar with the plugin but I'd be happy to try working on this myself if this is something you'd be interested in incorporating into the plugin.

**Comment by duracelltomi** [comment]
If the ct_before_builder action is being used to inject code just after the opening body tag, that can be easily added into GTM4WP

What other issues do you have using this theme and GTM4WP together?

**Comment by wkoehn** [comment]
No other issues that I know of. I added this code snippet and tested on one of my Oxygen built sites:

`<?php
 
add_action( 'ct_before_builder', 'gtm4wp_for_oxygen' );
/**
 * Adds gtm4wp tag code immediately after the opening <body> tag in Oxygen.
 */
function gtm4wp_for_oxygen() {
 
    if ( function_exists( 'gtm4wp_the_gtm_tag' ) ) {
        gtm4wp_the_gtm_tag();
    }
}`

I then tested with javascript disabled and it loaded the noscript tag as expected. Let me know if you need anything else. I can easily give you a testing site with Oxygen installed or you can access testing sites for 7 days from here: https://oxygenbuilder.com/try/

I'll spread the word in the oxygen facebook group once it's working. I was helping a member there yesterday is what got me thinking about this.

**Comment by duracelltomi** [comment]
Could you test another approach?

In frontend.php, at the end of the file you will see these lines:

`// compatibility with existing themes that natively support code injection after opening body tag
add_action( 'genesis_before', 'gtm4wp_wp_body_open' ); // Genisis theme
add_action( 'generate_before_header', 'gtm4wp_wp_body_open', 0 ); // GeneratePress theme
add_action( 'elementor/page_templates/canvas/before_content', 'gtm4wp_wp_body_open' ); // Elementor
`

Instead of your code, could you add this line after the lines above?

`add_action( 'ct_before_builder', 'gtm4wp_wp_body_open', 0 );`

**Comment by wkoehn** [comment]
Will test this afternoon.

**Comment by wkoehn** [comment]
I can confirm that this snippet added to frontend.php loads the <noscript> tag with JS disabled.

![image](https://user-images.githubusercontent.com/50601550/62637156-285b8f00-b8f8-11e9-9c95-b40d52d38558.png)

**Comment by wkoehn** [comment]
@duracelltomi I'm just finally getting around to testing this on a real site, and I'm finding that it does break the Oxygen editor when using the Codeless injection settings.

I've got a test site set up I can gladly give access to if you want to take a look or you can use this: https://oxygenbuilder.com/try/

It works fine on the front end, but Oxygen loads the site in an iframe I believe on the backend visual editor. Do you think it'd be possible to include a check to disable the plugin when on an editing URL?
For example, all Oxygen editing URLs look something like this: wpsandbox.pro/?ct_builder=true&ct_inner=true

**Comment by duracelltomi** [comment]
Hi,

I've applied this fix:
https://github.com/duracelltomi/gtm4wp/commit/79bf6f1164348fa9d631eeedb936c330f85663eb

It resolves the issue on this sandbox site:
http://plain-buffalo.w5.wpsandbox.pro/?ct_builder=true&ct_inner=true
