### ISSUE TITLE
WooCommerce alert boxes being closed automatically

### ISSUE THREAD

**Issue by colmtroy** [duracelltomi/gtm4wp#131]
Hi,
Reporting a suspected bug on a WooCommerce Single Product page with just WooCommerce and GTM4WP active.

Variable product.
2 variations.
https://xerostaging.commercegurus.com/shop/gender/mens/hana/

Steps to re-create:

1.) Open https://xerostaging.commercegurus.com/shop/gender/mens/hana/
2.) Click "Add to cart" (this is a negative test so don't make any variation selections) 
https://i.imgur.com/bqZEIqX.png
3.) Observe that the WooCommerce alert box flashes into view and then gets closed/supressed before the user can even see why.
http://www.giphy.com/gifs/VbnT0cT6LAhzg8Yhji

If I deactivate GTM4WP the alert box appears as normal.

### Active Plugins (2) ###

Google Tag Manager for Wordpress: by Thomas Geiger – 1.10
WooCommerce: by Automattic – 3.6.5

### Theme ###

Name: Twenty Seventeen

I've got WooCommerce integration active and can see gtm4wp.addProductToCart events being fired when I click the "Add to cart" button. I'm wondering if the reason this is happening is because GTM4WP is firing events when it shouldn't (i.e. I've not yet made a variation selection.)

?

**Comment by duracelltomi** [comment]
Hi,

I might not see this clearly: whan I add a product into the cart, what alert box flashes?
I see that the page reloads and the green "Successfully added to cart." message appears at the top of the page but does not gets closed automatically.

**Comment by colmtroy** [comment]
Hey @duracelltomi - the steps to re-create don't include making a variation selection :) Just open the link from Step 1 and then click the Add to Cart button. This will trigger the window alert box to open (as you've not made any variation selections). The problem is that the alert box doesn't stay open as one would expect to happen - it's starts flashing.

**Comment by duracelltomi** [comment]
Sorry for this late reply: I opened your site but I see a pre-selection of both the color and size attribute:
https://xerostaging.commercegurus.com/shop/gender/mens/hana/

I am opening the site in private browser mode with Chrome and Firefox

**Comment by colmtroy** [comment]
Hey @duracelltomi - yes I restored our staging site given the passage of time :)
I've now reset it to match the bug report conditions as set out in the original message.
If you try https://xerostaging.commercegurus.com/shop/gender/mens/hana/ now you'll see the issue.

**Comment by duracelltomi** [comment]
I can see that you have now also activated WooCommerce Google Analytics Pro.

When I press the add to cart button without selecting any product attribute, this message is shown:
![image](https://user-images.githubusercontent.com/7515949/63437731-5cbc6880-c42b-11e9-87f5-d5784f8d0ddc.png)

But this does not flash
