### ISSUE TITLE
Use product_id instead of remarketing_id for retrieving brand

### ISSUE THREAD

**Issue by WebVerder** [duracelltomi/gtm4wp#135]
I wanted to use the **"Taxonomy to be used for product brands"** feature but noticed I never actually got the brand in the datalayer.

After some investigation I noticed the function `gtm4wp_woocommerce_getproductterm()` used the remarketing_id, which is set to my SKU since we have the option **"Use SKU instead of ID"** active.

I don't think this was intended and is probably a bug ?

**Comment by Tofandel** [comment]
Just noticed the same issue, you beat me to it

Yes it's a bug, publishing a PR
