### ISSUE TITLE
Don't track for logged in users - please add option

### ISSUE THREAD

**Issue by travelmassive** [duracelltomi/gtm4wp#136]
This is a fantastic plugin, however I have one small request.

While I appreciate the sentiment to the answer in "Can I exclude certain user roles from being tracked?", I feel that this plugin should have the option to disable firing if the user is logged in.

Reasons:

1. It's simple to implement (and could be 2-3 lines of code in your plugin)
2. Adding a filter in GTM is more complex. For example - I host multiple web applications on the same domain, so I can't rely on the visitorType always being present when the tag fires. 
3. In 90% (guess) of install cases where this plugin is used on a public blog, there is no need to track logged in users as they will erroneously contribute to the page time / visitor count of the page. Therefore, it should be much simpler to disable for logged in users.

I love this plugin, except for this issue. I hope you'll take on board this feedback and add a pragmatic option to disable for logged in users.

In the meantime, I implemented a workaround to disable this plugin for logged in users, via a second plugin that neuters the option lookup. 

```
Folder -> plugins/aa-disable-google-analytics
File -> plugins/aa-disable-google-analytics.php (prefixed "aa" so we load first)
```

Contents of aa-disable-google-analytics.php:
```
/**
* Plugin Name: Disable Google Tag Manager for Logged in Users 
* Plugin URI: https://travelmassive.com/blog/
* Description: Disable Google Tag Manager for Logged in Users 
* Version: 1.0
* Author: Ian
* Author URI: https://travelmassive.com/ian
**/

// Disable Google Tag manager for logged in users

add_filter('pre_option_gtm4wp-options', 'pre_option_gtm4wp_options', 5, 1);

function pre_option_gtm4wp_options($options = array()) {

        // check cookies to see if we're logged in
        // we're too early for is_user_logged_in()
        foreach ($_COOKIE as $key => $value) {
                if (strpos($key, 'wordpress_logged_in') === 0) {
                        $options["gtm-code"] = "NOTRACKING"; // return invalid id
                        return $options;
                }
        }

        // otherwise, return options
        return $options;
}
```

Thanks! - Ian

**Comment by duracelltomi** [comment]
I need to think about this as this approach goes against my view about how GTM should be used :-)
But I also do not want to create a stiff position.

What you also need to see and consider: I can see the incoming support requests and I can see some new messages claiming that the plugin is not working or even negative WP.org reviews about this just because they have opted in to this option :-)

**Comment by travelmassive** [comment]
Perhaps as a compromise you could provide an "on/off" setting for _all_ logged in users, and if the site owner wishes to customise the behaviour based on roles, then you take them down the GTM path.

I see your point about people turning this feature on, then getting confused when they test their GTM and don't see the tag firing. Perhaps a visual cue on the navbar or console.log would avert this (ie: "GTM has been disabled for logged in users.").

If you take a look at the [steps needed](https://gtm4wp.com/how-to-articles/how-to-exclude-admin-users-from-being-tracked) to prevent the tag from firing from within GTM, it's quite an advanced set of steps. This is not for beginners, so I guess a lot of users skip this and are inadvertently tracking traffic they don't need to be.

For example, firing GTM for logged in users blows out the "time on site" stat since you are  editing/previewing a lot of articles all day long.

**Comment by duracelltomi** [comment]
OK, lets do it :-)

But an info banner + a console message will be definitely needed to minimise confusion
