### ISSUE TITLE
Use parent_id instead of product_id for retrieving brand if it's set/not 0

### ISSUE THREAD

**Issue by WebVerder** [duracelltomi/gtm4wp#137]
I'm using the "Taxonomy to be used for product brands" feature, and noticed I sometimes get (not set) in Analytics.

After some investigation I noticed the issue is most likely caused by using the product_id for variations, variations don't have the product attribute that is used for setting the brand assigned therefore it's necessary to check if the current product has a parent.

I think simply adding this code would do the trick:

```
$parent_id  = $product->get_parent_id();
if( !isset( $parent_id ) || $parent_id === 0 ){
  $parent_id = $product_id;
} 

...

gtm4wp_woocommerce_getproductterm( $parent_id, ... );
```

**Comment by duracelltomi** [comment]
Thanks for the note and the solution, I will add this into the core soon!
