### ISSUE TITLE
AMP Integration doesn't use Google's recommended approach

### ISSUE THREAD

**Issue by lucieslist-richcollins** [duracelltomi/gtm4wp#140]
This plugin uses amp-iframe instead of the Google recommended amp-analytics tag. I can't find any documentation online that recommends this approach.

Recommended integration:
<img width="717" alt="Screen Shot 2019-09-06 at 9 13 19 AM" src="https://user-images.githubusercontent.com/50151221/64443603-2ca9d200-d087-11e9-86c6-a184bd2b92fc.png">

**Comment by duracelltomi** [comment]
I do not know why you have seen any iframe tag, but in the source code the amp-analytics tag is used:
https://github.com/duracelltomi/gtm4wp/blob/master/integration/amp.php
