### ISSUE TITLE
Deleting dataLayer_content.* in JavaScript

### ISSUE THREAD

**Issue by tomaskavalek** [duracelltomi/gtm4wp#142]
I have never in datalayer data about transaction – transactionId, transactionDate, transactionType etc. Why?

Look at the code – especially condition here `if ( gtm4wp_orderid_tracked && ( dataLayer_content.transactionId == gtm4wp_orderid_tracked ) )` where you deleting these keys.

If `gtm4wp_orderid_tracked` is not stored in cookies, you create it from `dataLayer_content.ecommerce.purchase.actionField.id` and `dataLayer_content.transactionId` is filled from PHP right way, but the whole condition is `true` and these keys are missing in the datalayer even for the first time, in the time, when I need them, to track them in GTM.

What is wrong? I see that this is a new piece of code adden in last version. Can you help me? Everything is with same setup, but after update I don't have these data in datalayer.

File `public/frontend.php`:

```php
// fire WooCommerce order double tracking protection only if WooCommerce is active and user is on the order received page
if ( isset( $gtm4wp_options ) && ( $gtm4wp_options[ GTM4WP_OPTION_INTEGRATE_WCTRACKCLASSICEC ] || $gtm4wp_options[ GTM4WP_OPTION_INTEGRATE_WCTRACKENHANCEDEC ] ) && isset( $woocommerce ) && is_order_received_page() ) {

	$_gtm_header_content .= '
	// if dataLayer contains ecommerce purchase data, check whether it has been already tracked
	if ( dataLayer_content.transactionId || ( dataLayer_content.ecommerce && dataLayer_content.ecommerce.purchase ) ) {
		// read order id already tracked from cookies
		var gtm4wp_orderid_tracked = "";
		var gtm4wp_cookie = "; " + document.cookie;
		var gtm4wp_cookie_parts = gtm4wp_cookie.split( "; gtm4wp_orderid_tracked=" );
		if ( gtm4wp_cookie_parts.length == 2 ) {
			gtm4wp_orderid_tracked = gtm4wp_cookie_parts.pop().split(";").shift();
		}

		// check enhanced ecommerce
		if ( dataLayer_content.ecommerce && dataLayer_content.ecommerce.purchase ) {
			if ( gtm4wp_orderid_tracked && ( dataLayer_content.ecommerce.purchase.actionField.id == gtm4wp_orderid_tracked ) ) {
				delete dataLayer_content.ecommerce.purchase;
			} else {
				gtm4wp_orderid_tracked = dataLayer_content.ecommerce.purchase.actionField.id;
			}
		}

		// check standard ecommerce
		if ( dataLayer_content.transactionId ) {
			if ( gtm4wp_orderid_tracked && ( dataLayer_content.transactionId == gtm4wp_orderid_tracked ) ) {
				delete dataLayer_content.transactionId;
				delete dataLayer_content.transactionDate;
				delete dataLayer_content.transactionType;
				delete dataLayer_content.transactionAffiliation;
				delete dataLayer_content.transactionTotal;
				delete dataLayer_content.transactionShipping;
				delete dataLayer_content.transactionTax;
				delete dataLayer_content.transactionPaymentType;
				delete dataLayer_content.transactionCurrency;
				delete dataLayer_content.transactionShippingMethod;
				delete dataLayer_content.transactionPromoCode;
				delete dataLayer_content.transactionProducts;
			} else {
				gtm4wp_orderid_tracked = dataLayer_content.transactionId;
			}
		}

		if ( gtm4wp_orderid_tracked ) {
			var gtm4wp_orderid_cookie_expire = new Date();
			gtm4wp_orderid_cookie_expire.setTime( gtm4wp_orderid_cookie_expire.getTime() + (365*24*60*60*1000) );
			var gtm4wp_orderid_cookie_expires = "expires="+ gtm4wp_orderid_cookie_expire.toUTCString();
			document.cookie = "gtm4wp_orderid_tracked=" + gtm4wp_orderid_tracked + ";" + gtm4wp_orderid_cookie_expire + ";path=/";
		}

	}';
}

```

**Comment by duracelltomi** [comment]
Hi,

This code is new indeed and part of an additional layer of protection against double tracking of transactions. This has been an issue on mobile devices in the following case:

- user places the order on a mobile browser
- leaves the tab with the order received page open but closes the browser
- when this use opens the mobile browser couple of hours or days after the order, the order received page is reloaded from browser cache and the ecommerce data layer values pass the transaction to GA again
- since in that case no PHP code is executed, prevention in the PHP will not work

The code above checks a specific cookie set when the order received page is shown for the first time. If the page is re-run from browser cache, this code will make sure that the ecommerce data is removed so that GA does not track the same order twice.

**Comment by tomaskavalek** [comment]
Hi,

sorry, but it doesn't work for me even on desktop – Chrome, Safari. Especially `transactionTotal` is undefined, so I can't track conversion after placing an order.

So my opinion is, that the code is not okay – the JavaScript code and condition is always true.

**Comment by duracelltomi** [comment]
Do you have a sandbox site where I can place a test order without using my bank card?

**Comment by duracelltomi** [comment]
@tomaskavalek do you still need help here?
