### ISSUE TITLE
Support for custom taxonomies in data layer

### ISSUE THREAD

**Issue by duracelltomi** [duracelltomi/gtm4wp#15]
https://wordpress.org/support/topic/adding-custom-taxonomies-to-data-layer/

**Comment by rekkitatu** [comment]
This would be a nice feature addition. For example adding the product brand from a product custom attribute "pa_brand" to the dataLayer is something is missing from the Google analytics data without hard coding it now to the plugin. So maybe having some field that could be used to set the custom attribute/taxonomy keys would be the way to go for configuring the fields for the plugin to then pass to datalayer.

**Comment by f3bruary** [comment]
+1. I notice in Analytics it's lacking many useful variables like Brand and Product Category

**Comment by duracelltomi** [comment]
Product categories reporting should be part of enhanced ecommerce, are you sure you are missing this data? Product brands is a harder feature as this is not a native WooCommerce data and brand plugins usually add this with different methods.  I do not think I will be able to provide a general solution for this.

**Comment by f3bruary** [comment]
You're right about categories ! I was looking at a specific view which only showed 'not set'.

Also, I read here: https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce#product-data

There is a variable for brand. If you can let the user pick the attribute, e.g. 'pa_brand', and then use that attribute for brand, then maybe this can work ?

**Comment by duracelltomi** [comment]
For managing brands in WooCommerce enhanced ecommerce tracking, I have created another ticket:
https://github.com/duracelltomi/gtm4wp/issues/99
