### ISSUE TITLE
Provide WooCommerce product parent identifier in data layer

### ISSUE THREAD

**Issue by veetikaleva** [duracelltomi/gtm4wp#152]
Right now, the data layer `product.id` is set to the variant identifier. For our use case, we'd like to access the parent identifier in the data layer as well. Would this be possible?

**Comment by duracelltomi** [comment]
Do you need this only on the product detail page or other key pages as well?

**Comment by veetikaleva** [comment]
Everywhere.

On 14. Nov 2019, at 17.08, Thomas Geiger <notifications@github.com> wrote:

﻿

Do you need this only on the product detail page or other key pages as well?

**Comment by duracelltomi** [comment]
If you reply view email, please remove the original message as it lowers the readability of the thread on the web. Thanks!

There is a planned new feature which will provide more product data on the product detail page including the partner product ID. But this will be limited to the product detail pages.

On other pages, like a category page, this could hinder performance in a way that is not acceptable for many use cases. But using the WP hooks provided by GTM4WP you can add this functionality using a custom code on your site.

**Comment by pjwilson1977** [comment]
@duracelltomi 
Along with the extra product detail, is there a way to force to use the "primary category" when pusing to the dataLayer?
I have an issue where it pushes the last category based upon the chronological order, rather than a primary category.

**Comment by luukfiets** [comment]
@duracelltomi you mentioned the WP hooks GTM4WP provides, but I'm not able to find any documentation on the GTM4WP hooks. Can you point me in the right direction for those GTM4WP hooks?

**Comment by sebastiantheobald** [comment]
> @duracelltomi you mentioned the WP hooks GTM4WP provides, but I'm not able to find any documentation on the GTM4WP hooks. Can you point me in the right direction for those GTM4WP hooks?

Im also interested in a doco for the hooks. I want to implement the parent product id in the data layer.

**Comment by duracelltomi** [comment]
I created a page about all filters and actions provided by GTM4WP:
https://gtm4wp.com/gtm4wp-for-developers/actions-and-filters-in-gtm4wp-for-developers

**Comment by sebastiantheobald** [comment]
@duracelltomi thanks for that, sounds great :)!

I tried to implement your code this way just for testing: 

`
add_filter( 'gtm4wp_eec_product_array', 'my_product_filter', 10, 2 );

function my_product_filter( array $eec_product, string $ecommerce_action ): array {
	// add an attribute only on product detail pages
		$eec_product["dimension1"] = "Hello World"; // set a product scoped custom dimension

	return $eec_product;
}
`

This attribute now is added this way in the sourcecode: 
`<input type="hidden" name="gtm4wp_dimension1" value="Hello World" />`

within GTM, I can not see his attribute. Goal is to see it within the ecommerce.items array.. can you help me with that?

**Comment by duracelltomi** [comment]
If you wish to see this in GA4 reports, that is currently not possible yet. GA4 `items` array is converted from GA3 product data but GA4 currently does not have product scoped custom dimensions thus it is not possible to show this in GA4 reports in the way GA3 works.
