### ISSUE TITLE
All links have target=_blank appended

### ISSUE THREAD

**Issue by leigh-ols** [duracelltomi/gtm4wp#158]
When a sites domain is something like staging-www.blahblah.com all links are recognised as outbound due to the `www.` search/replace in `gtm4wp-outbound-click-tracker.js`

staging-www.blahblah.com becomes stagingblahblah.com.

Currently we have:
`var gtm4wp_localdomain = window.location.hostname.replace( "www.", "" );`

A better method would be:
`var gtm4wp_localdomain = window.location.hostname.split(".").splice(-2,2).join(".");`

Or if subdomains should be treated as outbound links, a check to see if the domain actually starts with 'www.' first:
`
var gtm4wp_localdomain = window.location.hostname;
if (window.location.hostname.startsWith('www.') {
    var gtm4wp_localdomain = window.location.hostname.replace( "www.", "" );
}
`

**Comment by duracelltomi** [comment]
Hi,

Sorry for this very long response time.
This will not be fixed as the whole outbound click tracking feature has been removed in the upcoming version.

You can use link click triggers inside your GTM container to track outbound clicks even in your special cases.
