### ISSUE TITLE
Links to brand pages redirect users to product detail page

### ISSUE THREAD

**Issue by duracelltomi** [duracelltomi/gtm4wp#16]
Product click event handler needs to check whether clicked link's href attribute points to the product detail page so that links pointing to other targets (like brand page) can still work:

http://www.etraper.pl/kategoria-produktu/odziez/meska/kurtki/

**Comment by gchodacki** [comment]
In my case for www.etraper.pl i solved this by add class for a href attribute and change in code
$( '.products li:not(.product-category) a:not(.add_to_cart_button,.brand,.upsells),.widget-product-item' ).click(function( event )
In my opinion this is the easiest way when we have a lot of plugins makes changes in display catalog or product pages

**Comment by duracelltomi** [comment]
I will try to add an additional check to the code so the links not pointing to the product detail pages do not get altered

**Comment by duracelltomi** [comment]
This has been fixed: an extra line of code checks whether the clicked link points to the product detail pages and does nothing if the link is pointing to another page (like a brand page):

https://github.com/duracelltomi/gtm4wp/commit/5c8a98feabca19601a9e95e7d3fe32b3c98f1f8f
