### ISSUE TITLE
Add "gtm4wp.orderCompletedEEC" to your HowTo article

### ISSUE THREAD

**Issue by eximius313** [duracelltomi/gtm4wp#161]
You have written a great article about configuring Enhanced Ecommerce tracking: https://gtm4wp.com/how-to-articles/how-to-setup-enhanced-ecommerce-tracking

The problem is, that in your regexp: `gtm4wp.addProductToCartEEC|gtm4wp.productClickEEC|gtm4wp.removeFromCartEEC|gtm4wp.checkoutOptionEEC|gtm4wp.changeDetailViewEEC` you are missing `gtm4wp.checkoutStepEEC` and `gtm4wp.orderCompletedEEC`
it should be
`gtm4wp.addProductToCartEEC|gtm4wp.productClickEEC|gtm4wp.removeFromCartEEC|gtm4wp.checkoutOptionEEC|gtm4wp.changeDetailViewEEC|gtm4wp.checkoutStepEEC|gtm4wp.orderCompletedEEC`
instead.
This is why a lot of people are complaining (some of them I helped on Facebook groups, some write to you directly: https://wordpress.org/support/topic/gtm4wp-ordercompletedeec-event-no-appear/)

I think it should be fixed :)

Moreover - while your artice is one of the best scored results when you search for "[setup enhanced ecommerce in woocomerce](https://www.google.com/search?q=setup+enhanced+ecommerce+in+woocomerce)", I could not find it on your website (even I knew its existence). I think it should be definitely placed in `How to articles` section.

**Comment by Alejopdp** [comment]
I worked for me!

> You have written a great article about configuring Enhanced Ecommerce tracking: https://gtm4wp.com/how-to-articles/how-to-setup-enhanced-ecommerce-tracking
> 
> The problem is, that in your regexp: `gtm4wp.addProductToCartEEC|gtm4wp.productClickEEC|gtm4wp.removeFromCartEEC|gtm4wp.checkoutOptionEEC|gtm4wp.changeDetailViewEEC` you are missing `gtm4wp.checkoutStepEEC` and `gtm4wp.orderCompletedEEC`
> it should be
> `gtm4wp.addProductToCartEEC|gtm4wp.productClickEEC|gtm4wp.removeFromCartEEC|gtm4wp.checkoutOptionEEC|gtm4wp.changeDetailViewEEC|gtm4wp.checkoutStepEEC|gtm4wp.orderCompletedEEC`
> instead.
> This is why a lot of people are complaining (some of them I helped on Facebook groups, some write to you directly: https://wordpress.org/support/topic/gtm4wp-ordercompletedeec-event-no-appear/)
> 
> I think it should be fixed :)
> 
> Moreover - while your artice is one of the best scored results when you search for "[setup enhanced ecommerce in woocomerce](https://www.google.com/search?q=setup+enhanced+ecommerce+in+woocomerce)", I could not find it on your website (even I knew its existence). I think it should be definitely placed in `How to articles` section.

It worked for me!! Thanks really.
