### ISSUE TITLE
"Do not flag orders as being tracked" description is unclear

### ISSUE THREAD

**Issue by eximius313** [duracelltomi/gtm4wp#163]
The description says:
```
Check this to prevent the plugin to flag orders as being already tracked.

This ensures that no order data will be tracked multiple times in any ad or measurement system so please only enable this feature if you really need it (with iDeal you might need this)!
```

mind the word "prevent". So if I enable, then I will *prevent* from double tracking.

But here: https://wordpress.org/support/topic/gtm4wp-ordercompletedeec-is-fired-after-refreshing/

you write:
```
Thanks, this is then the reason for what you see. If this checkbox is enabled, this is the expected behavior (refreshing the order received page will always include the transaction data)
```
So when the checkbox is enabled - refreshing will include transaction data.
Isn't it the other way around?

**Comment by duracelltomi** [comment]
If you turn on this option, all pageviews of the same order received page will inclulde the transaction data (thus you will track the same order multiple times)

If you leave this checkbox turned off, the plugin will do its best to detect all subsequent visits to the same order received page and will not output transaction data in those cases.
