### ISSUE TITLE
"gtm4wp.orderCompletedEEC" is fired even if user cancels transaction

### ISSUE THREAD

**Issue by eximius313** [duracelltomi/gtm4wp#164]
When User proceeds to the checkout, `gtm4wp.checkoutStepEEC` event is being fired (which is correct).
Then user proceeds to payment (for example PayPal) but then resigns from the payment and returns to the shop.
Even though WooCommerce correctly counts it as "Cancelled Order", gtm4wp still fires `gtm4wp.orderCompletedEEC` which causes Google Analytics to count this as success transaction and causes mismatch between GA and WooCommerce.
I think that something like `gtm4wp.orderCancelledEEC` should be fired instead?

**Comment by duracelltomi** [comment]
Sorry for this very late reply.

I tested this on my dev site and after cancelling my PayPal payment I've got back to the cart page and no orderCompleted tracking happened.
