### ISSUE TITLE
addProductToCart (EEC) is fired ignoring validation

### ISSUE THREAD

**Issue by luukskeur** [duracelltomi/gtm4wp#166]
First of all thanks to the good plugin! As some features are still in beta (like WooCommerce support) I'd like to make a enhancement to the add-to-cart event.

The event is fired based on a click event for the button:
https://github.com/duracelltomi/gtm4wp/blob/master/js/gtm4wp-woocommerce-enhanced.js#L144

This event should be fired based on [WooCommerce's custom jQuery events](https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/add-to-cart.js#L93) because they [already have validated](https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/add-to-cart.js#L73-L77) the input (of 3rd party plugins).

So in a nutshell, trigger `gtm4wp.addProductToCart` events based on:
`$( document.body ).trigger( 'adding_to_cart', [ $thisbutton, data ] );`

I think the best option is to hook into the adding_to_cart event because the 'added_to_cart' event is fired after the window.location redirect.

**Comment by hagsonz** [comment]
+1 for this one.
on product page, i am experiencing wrong addProductToCart ECC event fired because of a floating add to cart button which has add_to_cart_button (with ajax_add_to_cart) class.

this causing the event to grab the data from first item from my related products and send this as addProductToCart ECC event.

**Comment by duracelltomi** [comment]
Based on my testing `adding_to_cart` event is not triggered on single product detail pages after pressing the add to cart button.

**Comment by duracelltomi** [comment]
Hi,

Sorry for this late reply.

This idea (using the `added_to_cart` event) is not new to me however of you look closer to the [mentioned source code of WooCommerce](https://github.com/woocommerce/woocommerce/blob/5.8.0/assets/js/frontend/add-to-cart.js#L116), you will see that this trigger is not fired if WC is configured to redirect the user after card addition. Which means there can be many cases where add to cart tracking will be lost where it is working for now.

The event `adding_to_cart` would be more stable however this means we will still tracking events which might end up in an error.

**Comment by luukskeur** [comment]
Hi @duracelltomi , 

That is correct! Triggering on `adding_to_cart` however, is in my opinion still better then triggering on the button class which is more vulnerable for changes. `adding_to_cart` is in general a little more stable.

**Comment by duracelltomi** [comment]
I tested this code:

```
jQuery( document.body ).on( 'adding_to_cart', function( button, data ) {
  console.log("Button: ", button);
  console.log("Data: ", data);
  console.log("This: ", this);
});
```

On this page:
https://woo.gtm4wp.dev/product/hoodie-with-logo

... and the event handler was not triggered. Perhaps this is only suitable for tracking add to cart buttons in product lists?

**Comment by duracelltomi** [comment]
I was trying to find a solution but for the standard product detail page, the product form is just set to the backend using POST and processed there. So here I could only hook into the form submit event but that is also HTML/CSS dependent, I have seen customized product detail pages where this would break as well.

Also as far as I can see, as WooCommerce moves to Gutenberg as well, there might be different challenges in the (near?) future.

As long as the WooCommerce core does not have a single standard event that is fired in the browser when add to cart is really going to happen, any new approach to track this in GTM4WP will have scenarios where it will break.

I am really sorry, I would be more than happy to rewrite this part of the plugin but currently I do not see any better solution. I hope you understand that.
