### ISSUE TITLE
Variables for AMP Integration

### ISSUE THREAD

**Issue by luizyamada** [duracelltomi/gtm4wp#168]
According documentation, variables must be inside <script type="application/json "></script> tag
https://support.google.com/tagmanager/answer/9205783?hl=en

and line 142 of file https://github.com/duracelltomi/gtm4wp/blob/master/integration/amp.php
is and an extra {} on variables, resulting
{"vars":**{** {"pagePostType":"post" }**}** }
And, the correct format is
{"vars": {"pagePostType":"post" } }

**Comment by Paktas** [comment]
AMP is being phased out by Google. Wouldn't spend time on this.
