### ISSUE TITLE
gtm4wp-form-move-tracker.js results in <head> jQuery dependency

### ISSUE THREAD

**Issue by JordanPak** [duracelltomi/gtm4wp#172]
It looks like `/js/gtm4wp-form-move-tracker.js` is enqueued in the head, which isn't really a big deal, but unfortunately it's taking jQuery along with it since it's a dependency. We put a decent amount of effort into avoiding jQuery or at least making sure it isn't render-blocking. This is a great plugin, but it's the last one keeping jQuery in the `<head>`.

Since the usage of jQuery in the "move tracker" is pretty light, can it be adjusted to just use vanilla JS so jQuery can be removed as a dependency?

Alternatively, since everything in that file is basically a listener on `:input`, it should be safe to assume users won't be messing with inputs before the page loads, right? Maybe it can just be moved to the footer and vanilla JS won't really be needed?

**Comment by duracelltomi** [comment]
Hi,

Sorry for this very long response time.
I am going to release v1.12 shortly with Google Analytics 4 additions, just after that, the next big step will be to reduce/remove jQuery usage.

In the meanwhile, if you can help me updating plugin code, I would be happy to merge your PR

**Comment by duracelltomi** [comment]
Coming in v1.14:
https://github.com/duracelltomi/gtm4wp/commit/35cf9c5962213b153ccb36c63132d541f3de3582
