### ISSUE TITLE
gtm4wp.addProductToCartEEC not firing on Learts Theme

### ISSUE THREAD

**Issue by JoannaFaul** [duracelltomi/gtm4wp#175]
Hi ! 

I am using Learts Theme and Woocommerce (and website is https://www.crealoca.com/).
I tried to implement the gtm4wp plugin but the add to cart event is not firing at all on the product detail page (but working on a product list page).

I have checked for the "Add To Cart" button class ans this is correct (and set to .single_add_to_cart_button) as attached.

Where can I add the woocommerce_after_add_to_cart_button action ? Cause maybe this is what is missing ?
Within the theme editor and the woocommerce folder I do have a single-product folder but I don't have your add-to-cart folder inside so I don't know how to check whether this is implemented or not (and not used to enter within the theme editor section :P).

Many thanks !

<img width="420" alt="Capture d’écran 2020-11-03 à 18 45 08" src="https://user-images.githubusercontent.com/73904643/98028618-a6b22400-1e0e-11eb-9be3-2731faa09bb9.png">

**Comment by estereofonico** [comment]
I'm having the same situation with the Astra Theme. No solution found to comment. Seems like a bug to me.

**Comment by JoannaFaul** [comment]
OK, thanks to your answer, I will switch to another solution I think ^^. 
I didn't find an alternative so far asking around for a GTM plugin matching enhanced ecommerce.
But maybe I will quit GTM for this project to use only UA and send conversions from UA to GADS. Not the best solution to track Ads but there are more plugins to set up enhanced ecommerce for UA (not using GTM).

**Comment by wozniakm** [comment]
Most likely your theme bound its own handler to click event on this button and it's preventing gtm4wp plugin handler from firing. It is not plugin issue, it is your theme issue.

**Comment by JoannaFaul** [comment]
Hi, Thanks for the answer. Yes this is what I think too. I can't switch to another theme cause I am not working on my customer's website but only on the marketing part. I think that the theme can be modified to match the plugin but needs developments on the genuine theme files and I avoid modifying them (cause I don't know exactly what I am doing). So I am not using addToCartEvents and transactions seem to work fine so this is ok to run and optimize ads ;).
