### ISSUE TITLE
Add support for custom gtm.js source domain (server-side tagging)

### ISSUE THREAD

**Issue by henkisdabro** [duracelltomi/gtm4wp#178]
Based on recent developments around server-side tagging, there is now a way to load the standard GTM web container and gtm.js library from your own tagging server (given that you have one set up already). For those of us already using this feature it would be handy if there was a new box added into the GTM4WP "advanced" section for the user to enter your own custom tagging server URL. The effect would be to change the URL used within the GTM snippets injected by the GTM4WP plugin. 

For further details on the requirements, [Simo's article on the topic](https://www.simoahava.com/analytics/google-tag-manager-web-container-client-server-side-tagging/) is clearly illustrated. 

Let me know if you want more input or assistance.

**Comment by duracelltomi** [comment]
Hi,

Thanks, I am aware of this addition but currently my focus is on adding GA4 ecommerce data.
If you could lend a hand and implement this, I would be very happy to merge a PR from you.

I am not saying I will not add this into the core on my own but for me this has currently lower priority.

**Comment by ju1** [comment]
+1 for this (but since I don't know PHP, I can't help unfortunately).

**Comment by duracelltomi** [comment]
This has been added: https://github.com/duracelltomi/gtm4wp/commit/9891a74981e8be5b6bf1287465068beb783defcc
