### ISSUE TITLE
Purchase data layer event is triggered more than once

### ISSUE THREAD

**Issue by prichert2071** [duracelltomi/gtm4wp#181]
Hi,

The problem with multiple purchase events occurs on WooCommerce `/order-received` page. The event should be triggered only once, no matter how many times user visits that page. However, when going back and forth to the page, event is generated every time the page is visited.

I think there is a problem with file `public/frontend.php` on line `875`:
`window.localStorage.getItem( "gtm4wp_orderid_tracked" );`

Order ID is being taken, but the value is never assigned to any variable. For this reason data layer object is being pushed even if it should be blocked by finding order ID.

**Comment by duracelltomi** [comment]
Thanks for the report, this has been fixed: https://github.com/duracelltomi/gtm4wp/commit/0a973a481faec997ae6372e559f55888f57d6bc8
