### ISSUE TITLE
GA Checkout Options set to (not set)

### ISSUE THREAD

**Issue by WebLenn** [duracelltomi/gtm4wp#184]
Hi,

I'm wondering how we get the checkout options in Analytics, we followed the guides on GTM4WP and have setup the Enhanced Ecom tracking.
We do see the "checkoutOptionEEC" events in analytics but they have no label, when checking the Sales Performance and adding dimension "Checkout Options" the values are always set to (not set).

What is the appropriate way of adding the checkout options to GA ?
Do we need to create a new GA Tag for event "checkoutOptionEEC" where we do fill the Label & Value fields ?

Hopefully someone can point me in the right direction.

**Comment by WebLenn** [comment]
Hi,

Is there anyone who could help me out with this, I know this is probably not the best place to ask a question but after doing a lot of research I still can't figure out how to achieve this.
Could someone point me in the right direction or could point me to the appropriate place to ask this question ?

Thanks in advance.

**Comment by prabapro** [comment]
Hi @WebLenn,

If you're seeing `checkoutOptionEEC` event in your GA, meaning GTM4WP pushing the `gtm4wp.checkoutOptionEEC` event to the dataLayer. Not sure as to why `Checkout Options` dimension returns `(not set)`. Here's a screenshot of the same report;

![image](https://user-images.githubusercontent.com/32594937/117180362-bd532b00-adf1-11eb-8763-617d33331822.png)

To see the checkout options in your event tag, you may fire a dedicated GA event tag with a custom event trigger `gtm4wp.checkoutOptionEEC`. Let me share some screenshots of my implementation.

**Please note that below is **NOT A RECOMMENDED/APPROPRIATE** way of capturing checkout options or steps but the way I used to send data to GA.** 😄 

### Checkout Options Event Tag

![image](https://user-images.githubusercontent.com/32594937/117181775-3901a780-adf3-11eb-9ea6-2c01a601ded6.png)

- To get the checkout option from dataLayer, create a dataLayer variable with the value of `ecommerce.checkout_option.actionField.option`
- Trigger type: custom event
- Custom event name: `gtm4wp.checkoutOptionEEC`
- You may remove `gtm4wp.checkoutOptionEEC` from your existing e-commerce events trigger to avoided double-counting the events.

### Purchase Event with more details

In addition to the above, I do have an event for Purchase event with a few more additional info. This would help me to analyze my reports easily. I'm passing the below details as the event label;

`Transaction ID - Order Timestamp - Shipping Method - Payment Method`

![image](https://user-images.githubusercontent.com/32594937/117180550-eb386f80-adf1-11eb-94dc-a97ea0ec5b77.png)

- **Transaction ID** `ecommerce.transaction_id`
- **Order Timestamp** `orderData.attributes.date`
- **Shipping Method** `orderData.attributes.shipping_method`
- **Payment Method** `orderData.attributes.payment_method`

**Note**: To get the above values (except the transaction id), need to enable the below option in the plugin settings (`Integration > Woocommerce`)

![image](https://user-images.githubusercontent.com/32594937/117188440-b1b83200-adfa-11eb-91aa-c0fd9b263755.png)

![image](https://user-images.githubusercontent.com/32594937/117188868-28edc600-adfb-11eb-9ea1-b5ecdd8c6825.png)

**PS**: DO NOT enable the "use Data Layer" option in this tag.

Trigger Type: Custom Event
Custom Event: `gtm4wp.orderCompletedEEC`

Hope this helps. **I would highly recommend you test this thoroughly in your staging/dev server before implementing it to your live site.**

Thanks,
Praba.

**Comment by WebLenn** [comment]
Hi @prabapro,

Sorry for the late response, thanks a lot for the detailed reply.
Your way of sending it to GA may be a good solution for me since i can't discover the exact cause why it's currently not working.

Thanks again for taking the time to write a detailed reply, really appreciate it.

**Comment by prabapro** [comment]
Hey @WebLenn , you're most welcome :)
