### ISSUE TITLE
[Question] gtm4wp.orderCompletedEEC

### ISSUE THREAD

**Issue by prabapro** [duracelltomi/gtm4wp#188]
Hi Thomas,

Earlier, we didn't use gtm4wp.orderCompletedEEC to track purchases as the pageview tag itself takes care of this (with use dataLayer option). As per the revised documentation (from v1.12), once we include gtm4wp.orderCompletedEEC also to the trigger, would that double count the transactions (since the event tag is also overridden to use the dataLayer feature). Or GA would deduplicate the transaction? Please advise :)

Thanks,
Praba.

**Comment by duracelltomi** [comment]
Hi,

No, it won't, I will once more update the documentation with v1.13 soon since the enhanced ecommerce checkbox will be not needed in your GA pageview tag anymore.
