### ISSUE TITLE
Implement view_search_results

### ISSUE THREAD

**Issue by duracelltomi** [duracelltomi/gtm4wp#194]
The product list on a product search result page should use the view_search_results event in the GA4 implementation instead of view_item_list

To do so, we need to rewrite the code in gtm4wp-woocommerce-enhanced.js to first separate product list data into two lists, then fire the appropriate events for both lists.

**Comment by duracelltomi** [comment]
Official docs does not mention ecommerce parameters for this event:
https://developers.google.com/tag-platform/gtagjs/reference/events#view_search_results

**Comment by djwilko12** [comment]
Hi @duracelltomi ,
Cant you just push that view_search_results into the datalayer when the search occurs? Instead of using the view_item_list? On GA4 we can use custom data. Thanks

**Comment by duracelltomi** [comment]
This should be automatically fired if GA4 enhanced measurement's search tracking feature is turned on

https://support.google.com/analytics/answer/9216061?hl=en

**Comment by djwilko12** [comment]
Oh, you mean this will be tracked by GA4 itself... no need your plugin for that, right?

**Comment by duracelltomi** [comment]
Yes :-)
