### ISSUE TITLE
Your campaigns can't tailor dynamic ads based on user activity when your audience source doesn't send the required parameter.

### ISSUE THREAD

**Issue by GeorgeFR21** [duracelltomi/gtm4wp#196]
Hello there,

First of all, I would like to say this is a great plugin.

I use this for a while now and everything worked fine until some days ago that I received the error I placed on my post here as the title.

When everything used to work fine, I had used this post and done everything as described:

https://gtm4wp.com/how-to-articles/how-to-setup-dynamic-remarketing-in-google-ads-adwords

Are you aware of any google updates on this?

From the error message, I understand that now we do not send to google the Google Ads Business Vertical parameter which is the only required.

Other settings on my website: 

1. The global site tag for Google Analytics GA4 is installed on the /head of all pages.
2. The global site tag for Google Ads is installed on the /head of all pages.
3. Do I need to install on the /head section of my pages any event snippets from Google Ads?

Please, advise.

Thanks in advance,

George.

![3](https://user-images.githubusercontent.com/84437751/125160375-26a24200-e185-11eb-84b6-296d5cd6ee69.png)
![2](https://user-images.githubusercontent.com/84437751/125160377-27d36f00-e185-11eb-93dc-63043203ffd9.png)
![1](https://user-images.githubusercontent.com/84437751/125160378-286c0580-e185-11eb-94d3-b3ea69b5b8a4.png)

**Comment by duracelltomi** [comment]
Hi,

Sorry for this late reply.
Please post the URL of your site so that I can review what could went wrong.

Based on your screenshots, it should work.

One note: you do not need to install the global site tag manually as you need to handle all your GA or Google Ads related tagging in your Google Tag Manager container. If you added gtag() codes manually, that will be not populated with data by GTM4WP

**Comment by GeorgeFR21** [comment]
Hello there,

Thank you for your reply.

Fortunately, it seems that the issues went away and everything works fine again.

What I did, was to increase my daily budget at Google Ads campaigns, and then I started again to receive impressions and clicks.

I found that workaround from one of Google's Support Center open threads where a guy was facing the same issue with me.

As concerns the tagging, although I have installed the tags manually too, I am able to receive and view data on my GA property's events tab. What do you think?

Thanks in advance,

**Comment by duracelltomi** [comment]
> As concerns the tagging, although I have installed the tags manually too, I am able to receive and view data on my GA property's events tab. What do you think?

I usually prefer to use the native tag templates within GTM. This assures that the most recent, most up to date tracking codes are running on a site. Though gtag() is aimed to achieve the same goal, plugins like GTM4WP will usually support the tag template approach.

**Comment by GeorgeFR21** [comment]
Hello Tomi,

Ok, I see.

Thank you for this.

Best Regards,

George.
