### ISSUE TITLE
V1.13.1 -> V1.14.* breaks some clicks

### ISSUE THREAD

**Issue by StSaens** [duracelltomi/gtm4wp#206]
Hi. 
Longtime user here. And happy with your work.

Since upgrading from 1.13.1 to 1.14* I've noticed that a specific click doesn't work (=go to destination/page of the click) properly anymore. After disabling gtm4wp problem is solved. Also by downgrading from 14 to 13 the issue is resolved. 
Tested using Firefox 95.02
On Chrome 97.0.4692.71 the click does work after a noticable delay.

**To test:**
On my production (with 1.14*) if you go to my product (* removed due to instant load of bots) and scroll way down, you'll see the related products.
Click (not touchscreen) on either and see the site doesn't quickly go to the product you clicked.

On my staging (currently with v1.13.1) go to same product (* removed due to instant load of bots) and scroll down to related product.
Click on either and the site does go to the product.

I'm not too familiar with js debugging so atm I don't know the exact cause.

*I can supply the URLs to my production/staging in a DM.

**Comment by StSaens** [comment]
Done some more testing after loading 1.14.2 to my staging.

On Firefox, disabling Enhanced Tracking Protection changes the behaviour. It then waits 2 sec and loads the clicked product (instead of just stopping).
It has to do something with the callback timeout 'eventTimeout': 2000 in the part "// track clicks in product lists". I think there's something not 100% with the call(back) to GTM, but am not familiar enough with it to know how to handle this.

**Comment by duracelltomi** [comment]
This should solve the issue for you as well, could you test it on your instance as well?

https://github.com/duracelltomi/gtm4wp/commit/e228edcf7dfbef3ee5445de1165926fee22d0fd3

**Comment by StSaens** [comment]
Tested it on my staging and it works. Thanks for the quick work!

**Comment by StSaens** [comment]
@duracelltomi 
I tested some more on my iPad (iPadOS 15.2) and there I can see there is still a 2sec. pauze before the request (=go to product) is processed. So it seems Safari on iPad has a different kind of issue.
On my iPhone (iOS 15.2) also the same issue with the 2sec. timeout.

**Comment by duracelltomi** [comment]
What if you comment out the body of this function?

https://github.com/duracelltomi/gtm4wp/blob/master/integration/woocommerce.php#L1238

**Comment by StSaens** [comment]
I am assuming you mean wrapping the entire contents of the function in /* */, so it doesn't do anything.
Same thing (2 time out) happens.

**Comment by duracelltomi** [comment]
And reverting back to v1.13.* solve your iPad/iPhone issues as well?

**Comment by StSaens** [comment]
Just did a fresh test.

On 1.13.* the click is instant on iPad/iPhone.
On 1.14.2 the click has the 2 sec delay on iPad/iPhone.

Further info which is _very_ relevant I just noticed.
On my router I have some adblocking service running.

When I turn adblocking off:
1.13.*  = instant
1.14.* = instant
(iOS)

When I turn adblocking on:
1.13.* = instant
1.14.* = 2 sec. delay
(iOS)

So there is something different in the handling of this case since 1.14.*
Although it is a fringe case maybe. I don't know how many people/business are using adblocking packages.

**Comment by duracelltomi** [comment]
Hi,

In that case my assumption is that it blocks some tags in GTM.
The product click event handler is designed to stop the browser from loading the product detail page until all tags fired connected to the product click event. There is however a timeout set to 2ms. If tags can not end their job within 2sec, GTM continues the flow and fires the code that should run when all tags fired correctly.

So either way, the product detail page will be loaded (almost) immediately or after 2sec.

**Comment by StSaens** [comment]
Hi @duracelltomi ,
I found the error.

You accidentally nested a (ga4)  event into a ga3 event.

See line 757 for the ga3 event, and the following ga4 event is inside the execution of the ga3 event.  Line 772.
I fixed this on my staging and it's working properly now.

Let me know if this is indeed unintentional.

**Comment by StSaens** [comment]
Hi,
Alright, thanks for the info.
I'll just change the timeout to 500 every update. I don't believe a 2sec.
timeout for people blocking trackers is good UX.
Especially since more and more people are using (Analytics and/or Ad)
blockers.

Thanks for your time :)
