### ISSUE TITLE
Issue with old browser and optional chaining

### ISSUE THREAD

**Issue by edaquinta** [duracelltomi/gtm4wp#207]
The Optional chaining used in the line below is not working with old browsers. Can you do a more backward approach?
Thanks is advance!!!

https://github.com/duracelltomi/gtm4wp/blob/2acd59e4657fe315ae65a3ae81f9dfae517372e6/js/gtm4wp-form-move-tracker.js#L2

**Comment by duracelltomi** [comment]
Hi,

Could you tell me what percentage of your users are impacted by this?
And since WordPress core does not support any version of Internet Explorer anymore, I wouldn't count those users when calculating the ratio.

**Comment by edaquinta** [comment]
We have this errors quite often as you can see here (since yesterday), It always fail on the chaining saying `SyntaxError: Unexpected token '.'`. To be honest I can't tell the numbers about browser usage, but I know for sure IE is not the bulk. A lot of old Safari (12), and Chrome on Android, to name a few. 

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/8370362/149157158-f61cb19f-5c24-4ab8-90a3-0f92e78103a0.png">

**Comment by edaquinta** [comment]
Also, let me take the opportunity to thank you for the work you had put in in this plugin.

**Comment by duracelltomi** [comment]
Thanks for the kind words :-)

As far as I have seen, this usually relates to a smaller portion of site users.
What if I surround those blocks with try..catch and replace the error with a console warning about moving to a more modern browser/version? :-)

**Comment by edaquinta** [comment]
All you'll need to do is: `const elem = event.target && event.target.closest("input,select,textarea,button,meter,progress");`

That would have the same outcome and will not crash in old browsers. A bit uglier but as effective as the optional chaining.

**Comment by duracelltomi** [comment]
yes, I know, it is just that I feel so sad turning back to such solutions just to keep alive old rocks :-)

**Comment by edaquinta** [comment]
Actually, you don't have the optional chaining in the `focusout` and it seems to always work fine. Are does target will ever be `undefined`?

**Comment by duracelltomi** [comment]
I hope this will help :-)
https://github.com/duracelltomi/gtm4wp/commit/336033d5058a993021465158360f6bd7557e23b7

**Comment by edaquinta** [comment]
Wow! You went above and beyond. Really appreciated. Looking forward to the new release. Thanks
