### ISSUE TITLE
Use the primary category option of SEO plugins

### ISSUE THREAD

**Issue by duracelltomi** [duracelltomi/gtm4wp#208]
Original thread:
https://wordpress.org/support/topic/yoast-primary-category-2/

How to:
https://wordpress.org/support/topic/get-primary-category-2/
`get_post_meta( '$post_id', 'rank_math_primary_category', true );`

https://github.com/GSA/wordpress-seo/blob/master/inc/wpseo-functions.php
$primary_term_id = yoast_get_primary_term_id( 'taxonomy_slug', $post_id_or_object );

**Comment by duracelltomi** [comment]
Added: https://github.com/duracelltomi/gtm4wp/commit/dead2db88f123cfdeb54bd5f6c966dcca1e5c044

**Comment by Paktas** [comment]
Is this done only for Woocommerce products (as per comments on commits) only or for article posts as well?

**Comment by duracelltomi** [comment]
Currently only for WooCommerce products
