### ISSUE TITLE
gtm4wp.userRegistered not firing

### ISSUE THREAD

**Issue by dgreis** [duracelltomi/gtm4wp#210]
Longtime fan of this plugin. I think you're amazing. I was recently working on a site where I wanted to make use of the gtm4wp.userRegistered event after enabling it in the GTM4WP backend settings. But I couldn't get it to fire in GTM debug mode. To confirm it wasn't site specific, I created a simple user registration page on a dummy Wordpress site (v5.9) using the plugin [User Registration](https://docs.wpeverest.com/user-registration). Even then, however, I couldn't see the event fire in debug mode.

**Comment by duracelltomi** [comment]
Hi,

Sorry for this very long reply time, I just added a fix that could also solve this issue:
https://github.com/duracelltomi/gtm4wp/commit/7470b401f049f1cfc47f2fbc2d4ea9c04dff1f09
