### ISSUE TITLE
Events fire twice

### ISSUE THREAD

**Issue by carlosmdh** [duracelltomi/gtm4wp#211]
Hi
I have been testing the beta in debug mode of Google Tag Manager and I have observed that the events are activated twice in the Data Layer. On the one hand the gtm4wp... event is fired and on the other corresponding GA4 event (view_item, add_to_cart , view_cart...)
Is there any reason for it to be so?
Also, when you are on the shop page, the event that is launched has no name defined, so in the GTM debug console “message” appears instead of “view_item_list”

**Comment by duracelltomi** [comment]
Hi,

That is the expected behavior and it is working like that in the latest release as well. gtm4wp.* events include the Universal Analytics data layer. On the other hand view_item, add_to_cart, etc. include the GA4 data layer.

> Also, when you are on the shop page, the event that is launched has no name defined, so in the GTM debug console “message” appears instead of “view_item_list”

What is the setting of "Products per impression" in GTM4WP settings under the Integration - WooCommerce tab?

**Comment by carlosmdh** [comment]
Hi Tomi,
 
> That is the expected behavior and it is working like that in the latest release as well. gtm4wp.* events include the Universal Analytics data layer. On the other hand view_item, add_to_cart, etc. include the GA4 data layer.

OK, understand

> What is the setting of "Products per impression" in GTM4WP settings under the Integration - WooCommerce tab?

Default => 0 (Zero)

If you can, keep me informed of the evolution of the version so that I can translate it into Spanish when you release it.

Note: If you can, keep me informed of version evolution so that I can translate it into Spanish when you release it.

Regards

**Comment by duracelltomi** [comment]
Please set this value from 0 to 10 or 15 depending on how many products you have on a product list page. This will add the event names. From v1.15 this value will be defaulted to 10 and in a future version the value 0 will be deprecated and automatically incremented.

**Comment by carlosmdh** [comment]
Yes!!!
All working fine
Thkx
Regards
