### ISSUE TITLE
Post data push to dataLayer after Container Loaded event

### ISSUE THREAD

**Issue by carlosmdh** [duracelltomi/gtm4wp#212]
Hi tommy.

I've noticed that the post data (pagePostType, pagePostAuthor, pagePostDate...) is sent to the dataLayer for the first time after the Container Loaded event has been loaded, so it's not available to tags loaded in that moment, for example Google Analytics.

It seems that this also happens in version 1.14.2

Later, in other pages, if it loads before, specifically at the beginning, but not the first time.

Meanwhile, this data is sent to the data layer without an event name

Regards

**Comment by duracelltomi** [comment]
Hi @carlosmdh,

Sorry for this very late reply.
In your case I suspect that you've used manual container placement and somehow put the container code before the initial dataLayer.push().

Under normal circumstances, post data should be visible to tags firing on the "All pages" trigger.
