### ISSUE TITLE
Fatal error when saving settings under PHP 8.0

### ISSUE THREAD

**Issue by morvy** [duracelltomi/gtm4wp#215]
When I want to submit settings (like On/Off for container placement) I get this error message. It works fine on 7.3 and 7.4.

    Fatal error: Uncaught Error: implode(): Argument #2 ($array) must be of type ?array, string given
    in /wp-content/plugins/gtm4wp-master/admin/admin.php on line 914`

    Call stack:

    implode()
    wp-content/plugins/gtm4wp-master/admin/admin.php:914
    gtm4wp_sanitize_options()
    wp-includes/class-wp-hook.php:309
    WP_Hook::apply_filters()
    wp-includes/plugin.php:189
    apply_filters()
    wp-includes/formatting.php:4976
    sanitize_option()
    wp-includes/option.php:421
    update_option()
    wp-admin/options.php:322`

**Comment by duracelltomi** [comment]
Thanks!

Is this happening with v1.15 beta2?

**Comment by morvy** [comment]
Hi,

yes this is happening on both beta1 and beta2. Could be a server configuration issue, but I have no other hosting to test PHP8.0

**Comment by duracelltomi** [comment]
If this is happening with v1.15 beta, then it must be connected with this implode() call:

```
		} elseif ( $optionname == GTM4WP_OPTION_NOGTMFORLOGGEDIN ) {
			$output[ $optionname ] = implode(",", $newoptionvalue );

```

Could you test this code instead of the above?

```
		} elseif ( $optionname == GTM4WP_OPTION_NOGTMFORLOGGEDIN ) {
			if ( is_array( $newoptionvalue ) ) {
				$output[ $optionname ] = implode(",", $newoptionvalue );
			} else {
				$output[ $optionname ] = '';
			}

```

**Comment by morvy** [comment]
This did the trick, tested on 2 different VPS with PHP 8.0.3 and 8.0.10
