### ISSUE TITLE
Push dataLayer, but don't load GTM?

### ISSUE THREAD

**Issue by RomanAbashin** [duracelltomi/gtm4wp#216]
Cheers @duracelltomi , 
First: Thanks for all the hard work and tenacity. Love the plugin! <3

Now to the question:

## Context
My clients are using a variety of different consent solutions which need to load GTM by themselves for it to work properly. They do not handle it well if GTM is loaded externally.

## Question 
Is there a way to just push events to the DL *without* loading the GTM container? 

If yes, how to do it? I wasn't able to find it in the settings.

**Comment by morvy** [comment]
in latest beta, you can turn the container off, so the container is not inserted, but all push events remain in the code.

**Comment by duracelltomi** [comment]
The "Off" placement option also exists in v1.14 and older, in v1.15 the UI has been changed to give a better overview of options for plugin users.
