### ISSUE TITLE
item_list_id missing?

### ISSUE THREAD

**Issue by danielbarenkamp** [duracelltomi/gtm4wp#223]
Hello,

when viewing an item the "item_list_id" is missing? 

See: https://developers.google.com/analytics/devguides/collection/ga4/ecommerce?client_type=gtag#product_views_and_interactions

Is that a bug or do I miss any setting?

**Comment by duracelltomi** [comment]
As far as I know item_list_id is not a mandatory field. item_list_name is however populated and should be enough.
