### ISSUE TITLE
No security policy

### ISSUE THREAD

**Issue by hakusaro** [duracelltomi/gtm4wp#224]
Hi @duracelltomi,

Do you have a private email or contact information for security disclosures? If so, can you add that to your security policy on GitHub?

Cheers!

**Comment by duracelltomi** [comment]
Hi,

Not yet.
You can contact me in private via the [Facebook Page](https://facebook.com/gtm4wp) "messages" feature or a DM on [Twitter](https://twitter.com/gtm4wp). Or perhaps a message on [LinkedIn](https://www.linkedin.com/in/duracelltomi).

**Comment by hakusaro** [comment]
@duracelltomi I sent ya a couple DMs on twitter, from `hakusaro` (you can establish a chain of trust or contact me cryptographically using any verified identity at keybase.io/xn)

**Comment by duracelltomi** [comment]
Thanks, I received your message and started to apply a fix immediately
