### ISSUE TITLE
dataLayer push ecommerce should clear chache before push

### ISSUE THREAD

**Issue by gougou15005** [duracelltomi/gtm4wp#231]
I had some problems with the plugin and finally solved it by modifying some js. I set 10 products for each exposure, but my store has 12 products on one page. I should have sent two products in the second push, but I found that the datalayer displayed 10 products for the second time through tagmanager , this should not be normal, I'm not sure if this is a display error from google or if the data we sent was modified into wrong data. https://developers.google.com/tag-manager/enhanced-ecommerce
There are instructions to clear the ecommerce data before pushing and it worked fine after I did window[ gtm4wp_datalayer_name ].push({ ecommerce: null });

**Comment by duracelltomi** [comment]
Hi,

If you setup GA4 tracking using the container template here: https://gtm4wp.com/how-to-articles/how-to-setup-enhanced-ecommerce-tracking-google-analytics-4-ga4-version

... then there is no need to clear the ecommerce data in the data layer as the {{Ecommerce}} variable in the container template uses the "Version 1" Data Layer Variable which only reads the most recent pushed data and does not do recursive join.

**Comment by gougou15005** [comment]
> Hi,
> 
> If you setup GA4 tracking using the container template here: https://gtm4wp.com/how-to-articles/how-to-setup-enhanced-ecommerce-tracking-google-analytics-4-ga4-version
> 
> ... then there is no need to clear the ecommerce data in the data layer as the {{Ecommerce}} variable in the container template uses the "Version 1" Data Layer Variable which only reads the most recent pushed data and does not do recursive join.

Thank you, I will learn the knowledge of ga4 as soon as possible, but now the team members are more familiar with ga3, I can only make some modifications to make it work well
