### ISSUE TITLE
CheckoutStepEEC 

### ISSUE THREAD

**Issue by attraction11** [duracelltomi/gtm4wp#233]
Hello, thank you very much for your app. I meet a problem.
The CheckoutStepEEC event reports that the event of entering the page under Android webview is missing.
Presumably a bug of the plugin or a browser limitation

code location： duracelltomi-google-tag-manager/integration/woocommerce.php
``				
$data_layer['event']     = 'gtm4wp.checkoutStepEEC';
$data_layer['ecommerce'] = array(
	'currencyCode' => $currency_code,
	'checkout'     => array(
		'actionField' => array(
			'step' => 1 + (int) $gtm4wp_options[ GTM4WP_OPTION_INTEGRATE_WCEECCARTASFIRSTSTEP ],
		),
		'products'    => $gtm4wp_checkout_products,
	),
);
```

![image](https://user-images.githubusercontent.com/16067060/180603957-929f7584-d75f-4d11-b6bd-db1522c9e257.png)

![image](https://user-images.githubusercontent.com/16067060/180603798-8b056b3b-6fc0-4242-873d-c1034babc8f0.png)

**Comment by attraction11** [comment]
problem found，There is a problem with this judgment：
if ( array_key_exists( 'HTTP_X_REQUESTED_WITH', $_SERVER ) ) {		
		return $data_layer;
	}

**Comment by duracelltomi** [comment]
The mentioned lines prevent other issues to happen when the page is for some reason loaded via AJAX.

If would say the root cause of this issue is something else.
