### ISSUE TITLE
Important typo in blog 

### ISSUE THREAD

**Issue by luukfiets** [duracelltomi/gtm4wp#235]
@duracelltomi your blog on how to set up Google Ads conversion tracking for WooCommerce contains the following in step 4:

Shipping Postal Code: orderData,customer.shipping.postcode
Shipping Country: orderData,customer.shipping.country
Shipping Cost: orderData.totals.shipping_total

I think you made a typo. Shouldn't the comma between orderData and customer on the first two lines be a period?
orderData,customer.shipping.postcode > orderData.customer.shipping.postcode
orderData,customer.shipping.country > orderData.customer.shipping.country

Fixing it might prevent you from getting more support questions :)

**Comment by duracelltomi** [comment]
Thanks for the suggestion, indeed, that could help "some" people. I updated the article :-)
