### ISSUE TITLE
Orders cannot prevent from tracking with "_ga_tracked" key

### ISSUE THREAD

**Issue by in-codes** [duracelltomi/gtm4wp#236]
I have some scheduled orders which will pay only in future. But I don't want to track it by GA.
If I am right,  we can restrict orders from tracking by enabling "_ga_tracked" metavalue as 1.
used code => `update_post_meta( $order_id, '_ga_tracked', 1 );`

But when scheduled orders are processed and payment done, which is tracking from Thank you page ( from Order recieved page of woocommerce.) 

How can we prevent the orders from tracking?

**Comment by duracelltomi** [comment]
As discussed in your PR, I've added a fix for that, not the one you suggested but it should do the work.
