### ISSUE TITLE
Missing option for disabling Safari reload behavior. 

### ISSUE THREAD

**Issue by fschroiff** [duracelltomi/gtm4wp#239]
Please add a filter or an option for removing [the script](https://github.com/duracelltomi/gtm4wp/blob/fc59bbf6ec3cda6f94cfd3629a60f9390c5bcb59/integration/woocommerce.php#L1656-L1683) that causes all pages to reload in Safari when the back-button is used. 

This script breaks default and expected browser behavior.

**Comment by duracelltomi** [comment]
I removed this code completely:
https://github.com/duracelltomi/gtm4wp/commit/032067412fcb1e3b90979ec41a244ae477e538b1
