### ISSUE TITLE
Project not maintained

### ISSUE THREAD

**Issue by pinkasey** [duracelltomi/gtm4wp#240]
It seems that this project is not maintained anymore -
I see 3 open PR at the moment of writing this Issue, all very simple, and all without any reaction from the repository owner:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/1780369/192968836-282ab3ee-13bf-4415-b736-afac1fdfda23.png">
https://github.com/duracelltomi/gtm4wp/pull/238
https://github.com/duracelltomi/gtm4wp/pull/237
https://github.com/duracelltomi/gtm4wp/pull/217

I can understand if the maintainer has other things to do, and is not interested in maintaining this repo for free. 
I humbly suggest that he'd accept another maintainer(s), or add to the README.md a pointer to a successor fork - one of the (currently) 74 forks of this repository.

I would like to use the opportunity to thank everyone who worked on gtm4wp, and especially @duracelltomi - Thank you very much!

**Comment by duracelltomi** [comment]
I am here and development will be continued soon :-)

**Comment by pinkasey** [comment]
I'm very glad to hear it
thank you very much 😊

**Comment by pinkasey** [comment]
bump

**Comment by duracelltomi** [comment]
I have some projects ending next week, after that, you will see updates coming :-) (="soon")

**Comment by duracelltomi** [comment]
Yes, I am working on the next version and on reviewing PRs and issues in this repository :-)
