### ISSUE TITLE
Problem with view_item_list and Elementor

### ISSUE THREAD

**Issue by ribaunz** [duracelltomi/gtm4wp#241]
Hi, the event view_item_list isn’t fire in woocommerce with elementor theme called Riode.
The problem seems that product class isn’t show at start of the load but only after few seconds. If i set a delay with setTimeout the event is fired fine.
How can i solve this problem?
Thanks

**Comment by duracelltomi** [comment]
Hi,

Sorry for this late reply.
This seems to be some sort of edge case, I haven't heard any similar issue with other templates.

Although I do my best to support as many cases and template as possible, adding this setTimeout() call could break other sites.
