### ISSUE TITLE
History back button

### ISSUE THREAD

**Issue by jonasborneland** [duracelltomi/gtm4wp#244]
When clicking on a product from our category view, and then clicking history back it will jump back to the product again immediately. If you then click back again, it will skip the category view and go to the page you visited before that – it's like the category view dosen't exists in the browser history. 
Happens only when the archive page is cached.
Happens on both mobile and desktop.
Happens both with and without filters on.

**Comment by duracelltomi** [comment]
Hi,

Does this happen in all browsers or only in specific browsers?
Do you have any publicly accessible site where this happens?

**Comment by jonasborneland** [comment]
Hi @duracelltomi 
Thank you for answering.
It happens on all browsers i've tested on - Chrome, Safari, Safari iOS
You can test it here: https://petitvert.dk/produkt-kategori/udsalg/
Click a product and click history back.
If I disable GTM4WP it works fine again

**Comment by morvy** [comment]
@jonasborneland can't confirm on Firefox 107 / Windows 11 :(

**Comment by duracelltomi** [comment]
I can see it in Chrome (latest).
It is strange as it seems to execute a code that shouldn't execute when the back button is pressed

![image](https://user-images.githubusercontent.com/7515949/203164070-f11ef24a-5fef-4e54-897e-6b9d25536b56.png)

Perhaps I can include a check using `performance.navigation.type` to see whether the code is executing while the back/forward button was pressed
https://developer.mozilla.org/en-US/docs/Web/API/Navigation_timing_API/Using_Navigation_Timing

**Comment by jonasborneland** [comment]
@duracelltomi Thank you for checking
That would be great if that could fix it and work in the different browsers 🙏

I think this issue is related to this as well: https://wordpress.org/support/topic/bug-with-woocommerce-layered-nav-filters/

if that doesn’t work. Maybe popstate can be used to check, or in a combination? - I really don’t know much about history back events, but this seems to come up in google searches

https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event

“Browsers tend to handle the popstate event differently on page load. Chrome (prior to v34) and Safari always emit a popstate event on page load, but Firefox doesn't.”

**Comment by duracelltomi** [comment]
Do you have a testing version of your site where you could test my fix for this?

**Comment by duracelltomi** [comment]
Please make sure to have a backup of the original file before patching your live environment as this could go wrong at this stage.
Please apply these changes:
https://github.com/duracelltomi/gtm4wp/commit/b044efbf52f2f86e3d5f09846c0b5926c7420e22

**Comment by jonasborneland** [comment]
@duracelltomi 
Thanks! – The code is changed now, but did not have any effect

**Comment by duracelltomi** [comment]
That is way more interesting: when I hit the back button and the mentioned code above re-runs, browser says to the script the it is currently reloading the category page:

window.performance.getEntriesByType("navigation")[0].type: "reload"

I expected that this value will be "back_forward" which would be true since I just pressed the back button.
So the question is, why this is happening and why I can not reproduce this behavior on my dev site.

**Comment by jonasborneland** [comment]
@duracelltomi hmm yes I see that.
It is differently something to do with the cached pages. Non-cached pages does not have this problem.
Again if I disable the gtm4wp plugin, then it all works fine.

The strange thing is that gtm4wp is not loaded in the short moment the category page is hit before redirect back to the product page.
Can it have something to do with the browser history stack?

Only the 6 files in the middel is loaded before the page jumps back to the product page:
<img width="857" alt="Screen Shot 2022-11-22 at 4 01 05 PM" src="https://user-images.githubusercontent.com/6105278/203347961-eb747cab-c503-45ec-b0ed-0853e03249d3.png">

Also in safari, the first time you click back it with jump to category and then to the product. But if you click again it will skip the category page completely.

**Comment by jonasborneland** [comment]
> when I hit the back button and the mentioned code above re-runs

Okay, I might not be good at debugging – thought the file didn't load at all. So not sure what goes on 🙈

But I can tell that:
- It is differently something to do with the cached pages. Non-cached pages does not have this problem.
- if I disable the gtm4wp plugin, then it all works fine.

**Comment by duracelltomi** [comment]
What cache plugin are you using?

**Comment by jonasborneland** [comment]
Wp Rocket

**Comment by jonasborneland** [comment]
.. and Cloudflare for the static files + Cloudflare Rocket loader

**Comment by duracelltomi** [comment]
This site also uses WP Rocket and GTM4WP but does not use Cloudflare:

https://vitaminbolt.net/

And I do not experience this issue. Perhaps it is something to do with Cloudflare?

**Comment by jonasborneland** [comment]
Just tested from my iPhone 7 - that site does the same issue - I will check on desktop when I get home

**Comment by jonasborneland** [comment]
I also happens on desktop google chrome – but not everywhere and everytime.
But the products on the frontpage seems to have the issue more.
You can see in my videoe here, that it happen many of the times I try

https://user-images.githubusercontent.com/6105278/203415271-bc86ccc1-eb8f-479f-b932-7341631266db.mp4

I really hope you can help to solve the issue 🙏

**Comment by jonasborneland** [comment]
And when you use swipe back on iPhone as history back it happens a lot

**Comment by jonasborneland** [comment]
Let me know if I can do anything to help solving this? :)
And is it required for the plugin to manipulate the history for it to work correctly ?

**Comment by duracelltomi** [comment]
Here is another test that you can try:
https://raw.githubusercontent.com/duracelltomi/gtm4wp/master/js/gtm4wp-woocommerce-enhanced.js

(it seems to work on another live site with WP Rocket)

**Comment by jonasborneland** [comment]
@duracelltomi Thank you very much for all your help, I really appreciate it!
I will test this as soon as I can

**Comment by jonasborneland** [comment]
@duracelltomi  this seems to be working really well! I will continue to test, but I think it is fixed now 🥳
Thank you so much for all the help 🙏

**Comment by jonasborneland** [comment]
@duracelltomi Sorry for the late reply on this. But I will say that everything is fixed now, I have not had any problems anymore. Thank you so much for all your help!
