### ISSUE TITLE
ACF integration

### ISSUE THREAD

**Issue by Paktas** [duracelltomi/gtm4wp#247]
We are using the most popular custom field plugin ACF to store additional data for articles/posts (ex. internal article type, origin source).
These custom dimension need to go to Google Analytics along with other post data inside datalayer.

It would be great for GTM4WP to recognise custom fields from ACF to allow for their inclusion into datalayer via GTM4WP.
Couldn’t find any easy (non-developer) way.

**Comment by duracelltomi** [comment]
Good idea, I will see how this could be added to the plugin.

**Comment by duracelltomi** [comment]
This should do the work and also support other cases where ACF is not being used:
https://github.com/duracelltomi/gtm4wp/commit/b63f7d515c606ea9e4942a593c4b57478d6e6eee#diff-d4e1163390373688edafbdbef5bd28fc644b3625c37f4c95b5245fac4e4d47e1

Could you perhaps test it on a test site of yours?

**Comment by Paktas** [comment]
In your commit you wrote:
_Added: pagePostTerms data layer variable will now also include a meta key with post meta values that does not start with the _ character. This should allow to utilize custom fields added by plugins like Advanced Custom Fields._
We tested this part with ACF, but datalayer variables did not increase with ACF variables for articles.
Could you be more specific on how to add ACF varaibles into datalyer generated by GTM4WP?

**Comment by staniute** [comment]
Adding to the last Paktas' comment, even after updating the plugin with your provided code, in the console dataLayer we only see the items that have checkboxes checked on the plugin settings.

![image](https://user-images.githubusercontent.com/54246769/207576930-1200f871-4e91-4f9b-b213-822908c4e61b.png)
![image](https://user-images.githubusercontent.com/54246769/207577643-2bf367c8-7f29-442f-a6ec-164e7eeb1a04.png)

**Comment by duracelltomi** [comment]
You need to turn on "Post terms" under "Basic data->Post"

![image](https://user-images.githubusercontent.com/7515949/207658457-cea7ebf1-15de-4f9d-b28b-c5da4676fcf1.png)

You should see data in pagePostTerm.meta

**Comment by Paktas** [comment]
GTM4WP is now including ACF fields from inside `meta`.
At the same time including **ALL** of `meta` is too much data - there needs to be a possibility to pick ACF (or `meta`) fields that should go into datalayer.

**Comment by duracelltomi** [comment]
There can be so many various ACF entries, I am not sure how I could provide a filter mechanism to select only a few. Also , the current implementation also solves some other requests where users would like to include post scores of Yoast SEO or Rank Math SEO that is also stored in a post meta.

**Comment by nickmanderfield** [comment]
> There can be so many various ACF entries, I am not sure how I could provide a filter mechanism to select only a few. Also , the current implementation also solves some other requests where users would like to include post scores of Yoast SEO or Rank Math SEO that is also stored in a post meta.

Can add an input text box to the admin page if the meta checkbox is active/checked, make it an 'include only' input, one string per line, and run that against the array before it prints on the frontend. Assuming the user (us) will first run it with all meta enabled, then pick the ones we want, place them in that text box, and then save again.

This is what I will be implementing myself, as each post for some of my sites contain over 80 custom fields, I'd share my code here but it's not going to be written in any way I'd suggest someone else to use.

Fantastic feature as you've written it, will save a lot of people a lot of headache, thank you for the great plugin.

**Comment by nickmanderfield** [comment]
![GTM4WP-Sample+Code](https://user-images.githubusercontent.com/1288835/212484817-8a6318a1-4e3b-4950-befd-f6b3035ca39a.jpeg)

This worked for me, just needs a input to feed it. Can't suggest using it in prod since I am far from a programmer.

**Comment by Paktas** [comment]
> ![GTM4WP-Sample+Code](https://user-images.githubusercontent.com/1288835/212484817-8a6318a1-4e3b-4950-befd-f6b3035ca39a.jpeg)
> 
> This worked for me, just needs a input to feed it. Can't suggest using it in prod since I am far from a programmer.

Great option. Would love an input on UI (simple text) to list keys that needs to be included on datalayer from meta's.

**Comment by duracelltomi** [comment]
What if you could enter a regexp to filter meta fields outputed into the data layer?

**Comment by nickmanderfield** [comment]
> 

People would thoroughly enjoy this as a feature, not everybody, but those that need something like this would be THRILLED, as even having 'all' of it post to datalayer saved me a huge headache.

I would also say, and probably even less commonly, people use custom fields on taxonomy, I don't know much about how the data is stored, but it's possible it's very similar to how post custom fields are stored, may not be a big pain to add this as well?

**Comment by Paktas** [comment]
> What if you could enter a regexp to filter meta fields outputed into the data layer?

Regexp would be perfect for selecting.
Few examples into the selector field tooltip to make things easier in constructing one.

**Comment by Paktas** [comment]
Would it be possible to expect the rollout of the above regexp in the next release?

**Comment by duracelltomi** [comment]
I am doing my best, yes. I would like to focus on the next release in the coming days much more than I was able in the past weeks

**Comment by duracelltomi** [comment]
I reconsidered the regexp option as it is hard to validate (at least for me) and could introduce security issues.
Instead, I've added a new filter that can be used to limit what is being added to the data layer using your own logic: https://github.com/duracelltomi/gtm4wp/commit/e2b500e700bb688129608fe11cf932de51009469

**Comment by Paktas** [comment]
Do you mind explaining how to use this solution to include ACF fields in the data layer? It's not entirely clear from the commit above.
