### ISSUE TITLE
No hooks to filter purchase dataLayer, or customer data in dataLayer

### ISSUE THREAD

**Issue by vincedubroeucq** [duracelltomi/gtm4wp#252]
Hello,
Thanks for the plugin, it's very useful.

However I need to alter purchase information in the dataLayer, and there is no hook in the `gtm4wp_get_purchase_datalayer()` function to do so, in the `integration/woocommerce.php` file, line 412.

Adding a simple filter on the `return` statement on line 493 would allow developers to do so.

Also, doing the same for the `gtm4wp_woocommerce_datalayer_filter_items()` function l503 would allow for modifying customer data.

Is it possible to add a simple `apply_filters()` call on the return statement for these functions ?
It would be super helpful !
Thanks a lot !

**Comment by duracelltomi** [comment]
Here you are: https://github.com/duracelltomi/gtm4wp/commit/1e9a754f407865567f3c2019eb00dabb3f5c4080

**Comment by vincedubroeucq** [comment]
Thanks a lot !
I'll try that out !

**Comment by vincedubroeucq** [comment]
Hello !
Could you add the parameters used to build the datalayer ?
Basically : 
`apply_filters( 'gtm4wp_purchase_datalayer', $data_layer, $order, $order_items );`

?
Thanks a lot for your help !
