### ISSUE TITLE
How to surface Custom Parameters in GA4 Reports

### ISSUE THREAD

**Issue by DannyTaki** [duracelltomi/gtm4wp#255]
I've configured the plugin according to the documentation, and I can see the item data coming through in debug_view in GA4 and the tag is firing with the data in the variables.  How do I get these custom parameters' data into GA4 Reports?

**Comment by duracelltomi** [comment]
Item scoped custom dimensions were launched in GA4 just recently, you can use them to surface item parameters:
https://support.google.com/analytics/answer/10075209?hl=en

**Comment by DannyTaki** [comment]
When I try to create a custom definition in GA4, I don't see an option to give the definition 'item' scope, I can only choose from 'Event' and 'User'.
![image](https://user-images.githubusercontent.com/10076553/223623541-8bc542f9-4f94-4064-a06c-dcb03ff88914.png)

Right now my custom defintions looks like this and are all 'Event' Scope
![image](https://user-images.githubusercontent.com/10076553/223623630-7a13e082-692c-401b-8fca-8da2c1b5a25e.png)

**Comment by duracelltomi** [comment]
This new feature is rolling out globally, it may not appear in every property yet.
