### ISSUE TITLE
Track "undo" remove from cart

### ISSUE THREAD

**Issue by DavidKox** [duracelltomi/gtm4wp#26]
When removing a product from the cart a notice is displayed by WooCommerce with a link to undo the change and add the product back to the cart. When clicking on this link it would be great if the addToCart event would fire again.

**Comment by duracelltomi** [comment]
Note to self: woocommerce_cart_item_restored WP action could be used to detect this:
https://docs.woocommerce.com/wc-apidocs/source-class-WC_Cart.html#1004-1027

**Comment by duracelltomi** [comment]
This has been added to the dev version of the plugin
https://github.com/duracelltomi/gtm4wp/commit/52f29f499abe90942e1d09f0c3050446fc90d2fc
