### ISSUE TITLE
HPOS Support (High Performance Order Storage)

### ISSUE THREAD

**Issue by straightvisions-matthias-bathke** [duracelltomi/gtm4wp#263]
While High Performance Order Storage Feature in WooCommerce is stable and out of beta now, it would be great to have GTM4WP compatible with this critical performance feature.

https://woocommerce.com/document/high-performance-order-storage/

There were several support tickets created asking for this:
- https://wordpress.org/support/topic/hpos-support/
- https://wordpress.org/support/topic/hpos-compatibility-6/
- https://wordpress.org/support/topic/combability-with-high-performance-order-storage-3/

Most plugins using the standard function/api calls of WooCommerce won't need any changes except to confirm compatibility, see https://developer.woocommerce.com/2022/10/11/hpos-upgrade-faqs/ or as an example implementation https://github.com/hCaptcha/hcaptcha-wordpress-plugin/commit/98199353e92524be866bc880f7cb9e1a1c782f91

I've created this issue in github to give more attention to this topic to the developer community of this plugin.

**Comment by duracelltomi** [comment]
Here it is: https://github.com/duracelltomi/gtm4wp/commit/8e67ec516f35b124391c36151f534e61100432db
