### ISSUE TITLE
add-to-cart not fired on archive pages

### ISSUE THREAD

**Issue by dabesa** [duracelltomi/gtm4wp#276]
Dear support,
We have a website built on WPbakery.
We use the standard widget (WooCommerce products) on the homepage and category pages.
In these pages, the add-to-cart event is not fired when a product is added to cart.
It works fine on the single product pages.
How can we troubleshoot this?

Thanks

**Comment by duracelltomi** [comment]
Could you please post the URL of the site?

In general, the JS code of the plugin looks at this CSS selector:

`.add_to_cart_button:not(.product_type_variable, .product_type_grouped, .single_add_to_cart_button)`

If the HTML code of the product list page does not match this, GTM4WP will not catch clicks on add to cart buttons in a product list.

**Comment by dabesa** [comment]
Hi Thomas,
Thank you for the reply, but in the meantime we switched to another solution.
