### ISSUE TITLE
Push v1.17 to the WordPress repository

### ISSUE THREAD

**Issue by Dekadinious** [duracelltomi/gtm4wp#278]
HPOS will soon be standard on WooCommerce. Please push the version that added HPOS support 4 months ago to the WordPress repository.

Thanks!

**Comment by duracelltomi** [comment]
I thought it was pushed, just realized it is missing. I am on vacation, next week I will restart the engines :-)

**Comment by Dekadinious** [comment]
@duracelltomi Nice :)

We get a lot of critical errors on this new version. I believe it is because of non-existing order objects in some cases. I'll submit a PR with a fix for that as well :)

**Comment by GiovanniGoccia** [comment]
I installed 1.17 and I have these errors too, could you send me the fix while we wait for the official release?

**Comment by Dekadinious** [comment]
@GiovanniGoccia I believe it is already merged into master :)

**Comment by duracelltomi** [comment]
v1.18 is ready to be released, before that, could you do a quick test by updating your staging/testing sites from GitHub?
https://github.com/duracelltomi/gtm4wp/releases/tag/1.18beta1

**Comment by Dekadinious** [comment]
@duracelltomi Not seeing any errors on our staging platform while running through a normal order process :)
