### ISSUE TITLE
Unnecessary PHP notice

### ISSUE THREAD

**Issue by krautnerds** [duracelltomi/gtm4wp#28]
Hi there!

Im getting a PHP notice in the current version of gtm4wp in line 
https://github.com/duracelltomi/gtm4wp/blob/master/admin/admin.php#L887

"( ! ) Notice: Undefined index: plugintocheck in /wp-content/plugins/google-tag-manager/admin/admin.php on line 887"

My solution would be to set plugintocheck to NULL which would not break the current code:
```php
"plugintocheck" => isset($fielddata["plugintocheck"]) ? $fielddata["plugintocheck"] : null

```

**Comment by duracelltomi** [comment]
Thanks, I've added a check to the dev code, it will be included in the next plugin version
