### ISSUE TITLE
Reset ecommerce property before pushing new view_item or view_item_list event

### ISSUE THREAD

**Issue by luukfiets** [duracelltomi/gtm4wp#280]
Hi @duracelltomi, 

We are having an issue where our view_item event incorrectly sends multiple items to GA4. This is because the view_item_list event fires first and it has multiple items in the dataLayer.ecommerce property (which is correct). However, when the view_item is fired, the dataLayer.ecommerce property is not reset to null, so the old items (products) still exist in the dataLayer.ecommerce property. When the view_item event is fired with 1 product in it's event data, the first item in the ecommerce.items array is overwritten with the new item from the view_item event, but the other items in the ecommerce.items array will still exist.

I think we should include a dataLayer push with {ecommerce:null} before line 879 here: https://github.com/duracelltomi/gtm4wp/blob/9b0a741c371eb84f6c8cc74a50c8fb24bf346c2b/js/gtm4wp-woocommerce-enhanced.js#L878-L886

And we should probably do the same here right before line 377: https://github.com/duracelltomi/gtm4wp/blob/9b0a741c371eb84f6c8cc74a50c8fb24bf346c2b/js/gtm4wp-woocommerce-enhanced.js#L376-L383

I see this already came up in this issue: https://github.com/duracelltomi/gtm4wp/issues/231. It would be great if GTM4WP GA4 template container ([this one](https://gtm4wp.com/gtm-containers/gtm4wp-ga4-container-elements-20200419.json)) starts to use the dataLayer version 2 and if the code includes the {ecommerce: null} push

Best,
Luuk

**Comment by duracelltomi** [comment]
Hi,

Resetting the ecommerce object is not needed if you are using the native ecommerce integration of the GA4 event tag. I personally use this on many websites and there are no issues like yours.

Could you elaborate more on your setup?

**Comment by duracelltomi** [comment]
> as an agency we aren't just using GA4, but also Facebook, Instagram, TikTok and custom solutions as well

Personally I am an agency team member too, believe me, I can truly understand your situation :-)

> It seems that the default GA4 option uses data layer version 1 to get properties from the event model. This first version only gets the most recent value for a property. The newer version 2 merges properties if they have the same name. 

This is indeed the behavior

> Google recommended clearing the ecommerce object in their UA documentation:

That is right but it wasn't part of it before and as far as I know noone really explained the reasons for the change.
Existing implementations do not broke when Google changed this in their docs.

> With data layer version 1 it's not possible to access nested objects like ecommerce.items.

What we are using in our GTM container is the following:

1. we create a data layer variable that reads the whole ecommerce object but with Version 1 being set in the GTM variable options (let's suppose the name of the GTM variable is Ecommerce Object)
2. we then create a custom JS variable to read what we need, for example:

```
function() {
  var ecom = {{Ecommerce Object}};
  if (ecom) {
    return ecom.items;
  } else {
    return undefined;
  }
}
```

Or you can create a JS code that processes the `ecom.items` array further.

> I'm curious if clearing the ecommerce object would negatively impact your workflow.

Since the plugin is used in thousands of sites, I am not sure which existing implementation would break with such a change.
I saw the change in Google's docs when they did the change but was never brave enough to put this into GTM4WP because of the reasons above.

**Comment by luukfiets** [comment]
> That is right but it wasn't part of it before and as far as I know noone really explained the reasons for the change.
> 
> Existing implementations do not broke when Google changed this in their docs.

While I do get what you mean, I think it would still be useful to modify the setup. For most new websites the GA4 data layer structure should be used to be future proof. With the old UA data layer the products themself were in a different property in each ecommerce step (e.g ecommerce.detail.products and ecommerce.impressions and ecommerce.add.products). That way, new events on the same page would never really overwrite the old products array, since it was in a different property.

Now with the new GA4 structure the data layer setup is more standardized across different events, making it way easier to have the conflict reported in this ticket.


The work around with the v1 variable + JS for specific properties could work. I think multiple users manually add a variable to get the ecommerce object instead of using the one you provide in the GTM template. My main concern with that is that the default for variables is version 2. I think that the variable version is something that can be overseen easily, which then causes unexpected issues. 

> Since the plugin is used in thousands of sites, I am not sure which existing implementation would break with such a change.

I fully understand your point and I don’t want to push you into making changes you feel uncomfortable with. I’m trying to think of what could happen, but (un)fortunately nothing pops up in my mind. As far as I can see now, tags would still be fired and the ecommerce variables with v1 would still resolve to the value relevant for that event. No tags will be fired on the data layer push that clears the ecommerce object, unless they have a trigger that fires on all event anyway.

Please let me know your thoughts, I appreciate your time!

**Comment by duracelltomi** [comment]
What about having a checkbox in plugin options that you can turn on and it could output this ecommerce reset line.

Ecommerce codes will be rewritten soon as I will first deprecate, then remove Universal Analytics eec codes and GA4 version will be the only available code. While doing this rewrite, I can also introduce this new option.

**Comment by morvy** [comment]
@duracelltomi is the deprecation period necessary? I have like 80 UA and nearly all are off, forcing GA4 only.

Maybe you could just remove all the code and with the rewrite, you could introduce version 2.0 :)

**Comment by duracelltomi** [comment]
For GA360 customers UA is still collecting data. We also have such clients where some landing pages or micro sites are running on WP/Woo.

GTM setups need to be adjusted to switch to use the "Use GA4 data" option in UA tags. I would like to give a warning in the next version first and just then remove the codes. However, this time it won't take months to get there ;-)

**Comment by duracelltomi** [comment]
Here is the requested feature:
https://github.com/duracelltomi/gtm4wp/commit/930712e8f4bd3c254b0b4a1f525413ccef9069e4

You can see it in action on the dev site: https://woo.gtm4wp.dev/

**Comment by luukfiets** [comment]
Perfect, that looks good to me. Thanks for adding this option. How can I get you a coffee? :)

**Comment by duracelltomi** [comment]
What about here? :-)
https://github.com/sponsors/duracelltomi

**Comment by luukfiets** [comment]
Enjoy your coffee :)

**Comment by luukfiets** [comment]
Hi @duracelltomi, 

Do you have a rough estimate on when v19 will be released? Thanks for the info :)

**Comment by duracelltomi** [comment]
Hi,

I plan to release it on next Monday
