### ISSUE TITLE
Order Received Page - Blank <body> output

### ISSUE THREAD

**Issue by johnaps94** [duracelltomi/gtm4wp#282]
Hello!
We are facing the above behavior of a blank ' < body > ' in our order received page, with no visible php warnings when wp_debug is set to true.
Simply deactivating gtm4wp makes the problem go away...
Tried other things as well, but it seems it is solely coming from your plugin.
Have you had any other encounters of this as of yet?

**Comment by johnaps94** [comment]
i think your latest merge request (https://github.com/duracelltomi/gtm4wp/commit/6dfd0470eaaff600c95ae4d6d937d6c09c9bcb21)
fixed the problem!

I hope you dont forget to integrate this in the next update push on wp directory!

**Comment by morvy** [comment]
This is strange, I just checked Woo 8.0 and the function `is_returning_customer` wasn't touched. I'm testing the latest release too and have no errors in Sentry about this.

**Comment by morvy** [comment]
@johnaps94 can you try changing this

`$data_layer['new_customer'] = $order->is_returning_customer() === false;`

into this?

`$data_layer['new_customer'] = \Automattic\WooCommerce\Admin\API\Reports\Orders\Stats\DataStore::is_returning_customer($order) === false;`

**Comment by johnaps94** [comment]
it seems to do the trick, i will monitor it in the next few days...
i used
$data_layer['new_customer'] = method_exists($order, 'is_returning_customer') ? $order->is_returning_customer() === false : false;
in case the method wasnt accessible so i could resolve the bug...
Now i will be using yours, as it seems to also not produce the bug with the same tests...
$data_layer['new_customer'] = \Automattic\WooCommerce\Admin\API\Reports\Orders\Stats\DataStore::is_returning_customer($order) === false;
and monitor it...

**Comment by morvy** [comment]
The problem is, the is_returning_customer is in Order class, which only extends WC_Order. Order is used in admin, WC_Order both admin and frontend. The function in Order is only a wrapper for the DataStore static function so it should be stable with this approach.

@duracelltomi should I make a PR or is it enough info for you to change that line?

**Comment by duracelltomi** [comment]
@morvy a PR would be welcome at this point, but later I will update the code based on these informations

**Comment by duracelltomi** [comment]
v1.18 is ready to be released, before that, could you do a quick test by updating your staging/testing sites from GitHub?
https://github.com/duracelltomi/gtm4wp/releases/tag/1.18beta1

**Comment by morvy** [comment]
Tested on my local install, no issues (but should be tested at least by @johnaps94 as I somehow didn't have issues with the undefined function before)
