### ISSUE TITLE
Fatal error get_meta() in 1.17

### ISSUE THREAD

**Issue by GiovanniGoccia** [duracelltomi/gtm4wp#283]
in the previous version this error never happened

2023-08-07T05:36:26+00:00 CRITICAL Uncaught Error: Call to a member function get_meta() on null in /var/www/vhosts/xxx/httpdocs/wp-content/plugins/duracelltomi-google-tag-manager/integration/woocommerce.php:842
Stack trace:
#0 /var/www/vhosts/xxx/httpdocs/wp-includes/class-wp-hook.php(308): gtm4wp_woocommerce_datalayer_filter_items()
#1 /var/www/vhosts/xxx/httpdocs/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#2 /var/www/vhosts/xxx/httpdocs/wp-content/plugins/duracelltomi-google-tag-manager/public/frontend.php(998): apply_filters()
#3 /var/www/vhosts/xxx/httpdocs/wp-includes/class-wp-hook.php(306): gtm4wp_wp_header_begin()
#4 /var/www/vhosts/xxx/httpdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /var/www/vhosts/xxx/httpdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /var/www/vhosts/xxx/httpdocs/wp-includes/general-template.php(3049): do_action()
#7 /var/www/vhosts/xxx/httpdocs/wp-content/themes/oceanwp-child/header.php(13): wp_head()
#8 /var/www/vhosts/xxx/httpdocs/wp-includes/template.php(783): require_once('...')
#9 /var/www/vhosts/xxx/httpdocs/wp-includes/template.php(718): load_template()
#10 /var/www/vhosts/xxx/httpdocs/wp-includes/general-template.php(48): locate_template()
#11 /var/www/vhosts/xxx/httpdocs/wp-content/themes/oceanwp/page.php(12): get_header()
#12 /var/www/vhosts/xxx/httpdocs/wp-includes/template-loader.php(106): include('...')
#13 /var/www/vhosts/xxx/httpdocs/wp-blog-header.php(19): require_once('...')
#14 /var/www/vhosts/xxx/httpdocs/index.php(17): require('...')
#15 {main}
  thrown in /var/www/vhosts/xxx/httpdocs/wp-content/plugins/duracelltomi-google-tag-manager/integration/woocommerce.php alla riga 842

**Comment by duracelltomi** [comment]
This has been fixed in https://github.com/duracelltomi/gtm4wp/commit/6dfd0470eaaff600c95ae4d6d937d6c09c9bcb21
