### ISSUE TITLE
Notice: Undefined variable: blocking_cookie

### ISSUE THREAD

**Issue by cyang2492** [duracelltomi/gtm4wp#288]
We're getting this notice warning on top of the site after installing this plugin.

Notice: Undefined variable: blocking_cookie in /homepages/45/d343080493/htdocs/wp-content/plugins/duracelltomi-google-tag-manager/public/frontend.php on line 603

Anyone else have this issue and know how to fix it?

**Comment by morvy** [comment]
Try to put `$blocking_cookie = false;` on line 591

**Comment by cyang2492** [comment]
Got it, that worked THANKS!

**Comment by duracelltomi** [comment]
Fixed in https://github.com/duracelltomi/gtm4wp/commit/c66db65a0b2286464bbc42138c585f2cc5a7b68b
