### ISSUE TITLE
String vs integer in add_to_cart

### ISSUE THREAD

**Issue by StSaens** [duracelltomi/gtm4wp#289]
Hi,
Google's documentation: 
https://developers.google.com/analytics/devguides/collection/ga4/ecommerce?client_type=gtag#add_or_remove_an_item_from_a_shopping_cart
and 
https://developers.google.com/analytics/devguides/collection/ga4/reference/events?client_type=gtag#select_item
 shows that "item_id" should be a string.
```
items: [
    {
      item_id: "SKU_12345",
      item_name: "Stan and Friends Tee",

```

In gtm4wp's messages to datalayer this field is an int. Can this be straightened?

GTM4WP:
```
    "items": [
      {
        "item_id": 39910,
        "item_name": "test product",

```

**Comment by duracelltomi** [comment]
Hi,

What about these changes?
https://github.com/duracelltomi/gtm4wp/commit/93e49ba3220ae35aa2744812c98c64893644686c

**Comment by StSaens** [comment]
Looks good to me. Thanks for your quick work!
