### ISSUE TITLE
Add geo location to the data layer

### ISSUE THREAD

**Issue by duracelltomi** [duracelltomi/gtm4wp#29]
> wondered if it would be easy to add users location to the datalayer, i know you’re already using it for the weather tracking (which is super awesome in itself), just seems like it be crazy useful to be able to access the location for custom tags too.

https://wordpress.org/support/topic/location-in-datalayer/

**Comment by accetturo** [comment]
I would assume the best way to do this would be with MaxMind, which can be installed for geolocation. I do not know of any Free API's that are available with this data, but it can be installed locally for free.

http://dev.maxmind.com/geoip/geoip2/geolite2/
