### ISSUE TITLE
Missing surrounding "products" key in gtm4wp.changeDetailViewEEC event

### ISSUE THREAD

**Issue by DavidKox** [duracelltomi/gtm4wp#30]
According to Googles documentation the implementation of the "measuring views on product details" is missing the enclosing "products" under "detail" in the "gtm4wp.changeDetailViewEEC" event.
Currently the data is written directly into the "detail" element.
See: https://developers.google.com/tag-manager/enhanced-ecommerce
And: https://github.com/duracelltomi/gtm4wp/blob/master/integration/woocommerce.php#L115

**Comment by duracelltomi** [comment]
You are right, I added the fix that will be included in v1.7
