### ISSUE TITLE
Unprotected headers used for IP address

### ISSUE THREAD

**Issue by dnutbourneudp** [duracelltomi/gtm4wp#307]
The routine `gtm4wp_get_user_ip()` treats the HTTP header `X-Forwarded-For` as the (first choice for the) visitor's IP address, even though this header is not protected and can be spoofed by any visitor at will. More info: https://www.stackhawk.com/blog/do-you-trust-your-x-forwarded-for-header/. 

Failing this (i.e. if the header is not present) the code then goes on to instead try several other headers, several of which are also under direct visitor control. PHP code should only use `$_SERVER['REMOTE_ADDR']`, relying upon the server administrator to have correctly configured the server to make sure that this contains the trusted remote IP address; and can also include a setting to allow the site owner to use something else (i.e. something that the site owner knows on their setup is trusted and not user-supplied).

As code in the plugin does do some checks on the data to make sure it's a valid IP address, so the problems caused by the defect are limited to allowing a malicious attacker to fabricate unlimited bogus data, rather than hack into the site.

**Comment by duracelltomi** [comment]
Hi,

Thanks for the report.

So you suggest introducing a custom field in the plugin where one can enter a custom header name that the plugin will use instead of iterating through known headers and only use REMOTE_ADDR if this is not set?

**Comment by dnutbourneudp** [comment]
Hi,

The default should be `$_SERVER['REMOTE_ADDR']`, rather than an unprotected header.
Having the option to switch to using a header (either totally custom by the user or from a pre-populated list of known headers) would then be potentially useful as a fallback

**Comment by duracelltomi** [comment]
What do you think of this change?

https://github.com/duracelltomi/gtm4wp/commit/18d7e478798aa6fed99c66f78c1611cf5acdd617

**Comment by dnutbourneudp** [comment]
Sorry for the delay. I think that change should cover the issue
