### ISSUE TITLE
Cannot track add to cart event on products lists

### ISSUE THREAD

**Issue by Kratzfactory** [duracelltomi/gtm4wp#317]
I have a problem on webshop pocketmonster.dk - all is working well except tracking add to cart events on products list (it works on product detail pages). Can some1 see why this is not working? 

Thanks
Jacob

**Comment by duracelltomi** [comment]
Hi,

Add to cart buttons in your product lists include the `single_add_to_cart_button` CSS class which prevents the add_to_cart event to fire. There is a different logic in GTM4WP to fire add_to_cart on single product detail pages and product list pages. Removing this class solved for me the event tracking however the design of your add to cart button broke.

You should separate functionality and design in CSS classes as well: do not add the class `single_add_to_cart_button` just because this makes the button look like the proper way (IMHO).

**Comment by Kratzfactory** [comment]
Hallo and thank you for this! So you would use the standard: class="button product_type_simple add_to_cart_button ajax_add_to_cart" or what?

**Comment by Kratzfactory** [comment]
I changed the class, and it is working thanks. 

But now the view_listing_items are fired 3 times on product listing pages. How can I check why this is suddently happening. This was not here yeasterday. 

![image](https://github.com/duracelltomi/gtm4wp/assets/51082297/52bff7de-22b8-4aa9-9a57-2f6acf0f5e28)

**Comment by duracelltomi** [comment]
This should be normal, GTM4WP splits larger product lists into smaller chunks to prevent dataloss. A single hit can only include 16kB of data, with lots of products in a list, this could be an issue. Splitting the data into multiple events can solve that.

**Comment by Kratzfactory** [comment]
Hello Thomas,

I hope you’re doing well! I’ve run into an issue with the Google Tag
Manager plugin on my WooCommerce shop and was hoping you might be able to
help.

It seems like the user-generated dataLayer variables only get populated
when a customer is logged in. Since most of my customers don’t log in when
browsing or purchasing, this is causing some problems with tracking.

Is this a known issue, or is there something I can adjust to make the
dataLayer work for all users, regardless of their login status?

I’d really appreciate any tips or guidance you can share. Let me know if
you need more details to look into this!

Thanks so much for your help.

Best regards,
Jacob

Den man. 15. jan. 2024 kl. 09.50 skrev Thomas Geiger <
***@***.***>:

**Comment by duracelltomi** [comment]
Hi,

To use customer data to populate user defined variables, please use the order data in the data layer as described in this article:
https://gtm4wp.com/google-tag-manager-for-woocommerce/enhanced-conversions-for-google-ads-with-woocommerce-how-to-setup

You will need to enable Integration->WooCommerce->Order data in data layer checkbox to make this work.
