### ISSUE TITLE
User data for Enhanced Ecommerce

### ISSUE THREAD

**Issue by luanfernandes** [duracelltomi/gtm4wp#319]
Hey, I don't know if this is the right place, sorry if it is not. 

I wanna give google my customer's email addresses but I don't know if this is the correct way.. I added customerBillingPhone as a custom variable but my event is 'purchase' not 'gtm4wp.orderCompletedEEC' (I followed gtm4wp tutorial and template). Will it work or should I use ordercompletedEEC as my trigger?

**Comment by duracelltomi** [comment]
Hi,

I am not sure which tutorial you are referring to, the conversion tracking tutorial does not mention enhanced conversions (yet)
https://gtm4wp.com/google-tag-manager-for-woocommerce/how-to-setup-google-ads-conversion-tracking-for-woocommerce

It mentions the purchase trigger and you should use this to trigger conversion tags.

customerBilling* variables could be empty for guest checkouts, I would recommend to activate the option in GTM4WP to include order data on the order received page and use orderData.customer.emailhash, orderData.customer.first_name, etc data layer variables instead.

**Comment by luanfernandes** [comment]
Hey @duracelltomi , thanks for the fast answer! Yes I was referring to this tutorial but I wanted to use enhanced conversions so I just added the customer email variable there. 

I'm using 'purchase' as the trigger right now, so my question was if I need to change it to ordercompletedEEC.

_"customerBilling* variables could be empty for guest checkouts"_
Thanks! Will change that. I tested in only 1 website and it worked with that one but you are right, I should use order data. 

So, to be clear, I'm just asking even if I'm using 'purchase' as my trigger, the customer data will be available for me to use?

**Comment by duracelltomi** [comment]
> I'm using 'purchase' as the trigger right now, so my question was if I need to change it to ordercompletedEEC.

No, purchase should be used. gtm4wp.orderCompletedEEC has been deprecated and will be removed very soon: 
https://gtm4wp.com/announcements/be-prepared-to-big-changes-in-gtm4wp-v1-20.html

**Comment by luanfernandes** [comment]
Ok good to know, thanks!
