### ISSUE TITLE
Google Tag Manager is loaded even though setting is turned off

### ISSUE THREAD

**Issue by ctekk7** [duracelltomi/gtm4wp#323]
In the newest version 1.19.x & 1.20 it seems that google tag manager container is loaded even though "Container code ON/OFF" is set to OFF.

Also setting to “manual placement” doesn’t work anymore, the container is still loaded.

When I deactivate the plugin GTM Container isn't loaded anymore. 

probably connected reports:
https://wordpress.org/support/topic/container-code-on-off-but-still-showing/

_**Update:
After some testing I found out, that this issue only occurs if you have following option enabled:
Do not use console.log() messages on frontend**_

**Comment by nikedike** [comment]
We have the same issue (my thread). Any chance to get some info on this?

**Comment by ctekk7** [comment]
After some testing I found out, that this issue only occurs if you have following option enabled:
Do not use console.log() messages on frontend

**Comment by dane206** [comment]
We have the same issue, however, we took it one step further and completely deactivated, removed, and deleted the plugin, yet the issue remains...

We're unclear on how to prevent the 2nd gtm container load (which creates a 2nd 'gtm.start' and leads to additional unexpected data issues).

How can this be resolved?

Also added comment to the discussion here: https://github.com/duracelltomi/gtm4wp/issues/323#issuecomment-1961725477

Thanks!

**Comment by morvy** [comment]
if you removed this plugin, there is no way it can magically add GTM script back. Disable all plugins and try one by one (or at least, disable those that may have something to do with tracking)

**Comment by ctekk7** [comment]
> if you removed this plugin, there is no way it can magically add GTM script back. Disable all plugins and try one by one (or at least, disable those that may have something to do with tracking)

well I guess there could be a way but it is unlikely and it is not related to my bug. when I deactivated the plugin the GTM container wasn't loaded anymore.

**Comment by duracelltomi** [comment]
Gentleman, without an URL I can not tell you why this can happen.
What is for sure: when GTM4WP is deactivated, there is no way for the plugin to add any container code to your site.

**Comment by ctekk7** [comment]
> Gentleman, without an URL I can not tell you why this can happen. What is for sure: when GTM4WP is deactivated, there is no way for the plugin to add any container code to your site.

As I said, it's connected to "Do not use console.log() messages on frontend" option. 

Steps to reproduce:
Set "Container code ON/OFF" to off.

- When I deactivate "Do not use console.log() messages on frontend" the GTM container isn't loaded anymore.
- When I activate "Do not use console.log() messages on frontend" it's loaded (which shouldn't be).

**Comment by morvy** [comment]
this is very, very strange .. I experience the same issue on sites where I updated to latest GTM4WP (1.20)

As soon as I disable console.log there is GTM container loaded, even if it's set to OFF. I checked the code, there is no connection between $no_console_log and GTM init tag. I have to keep it disabled, because Complianz Premium and their "integration" with GTM4WP is buggy, it doesn't change consents at all..

**Comment by ctekk7** [comment]
> this is very, very strange .. I experience the same issue on sites where I updated to latest GTM4WP (1.20)
> 
> As soon as I disable console.log there is GTM container loaded, even if it's set to OFF. I checked the code, there is no connection between $no_console_log and GTM init tag. I have to keep it disabled, because Complianz Premium and their "integration" with GTM4WP is buggy, it doesn't change consents at all..

I remember going through the code and I think I saw the connection.

**Comment by Blueboots** [comment]
Same problem here.

- I need to turn off the container in GTM4WP as it will be added through a consent plugin (using GDPR Cookie Compliance by Mooveagency, which I am not a fan of but there we go).
- When container placement is off, the website users get blasted with the console warning messages.
- So, I use the option to turn that off, and this bug makes itself known. The container appears even though it should be deactivated.

This post has a bit more info from someone experiencing the same. https://wordpress.org/support/topic/container-code-off-but-still-injecting-code/

As everyone is dealing with the consent issue right now I imagine this issue will be cropping up for a lot of users of the plugin.

**Comment by morvy** [comment]
@ctekk7 you were right, found it, fixed it :) let's wait for Thomas to approve and push an update to repository

@Blueboots thanks for pointing to right direction 👍

**Comment by duracelltomi** [comment]
Thanks everyone for the contribution, I just merged the fix and will release v1.20.1 soon
