### ISSUE TITLE
String vs id in view_item_details

### ISSUE THREAD

**Issue by StSaens** [duracelltomi/gtm4wp#325]
Hi,
Google specifies id to be a string in view_item_details (and possibly others) event (https://developers.google.com/analytics/devguides/collection/ga4/ecommerce?client_type=gtag#view_item_details)

In your code it's an integer. While not an issue within ga4, it does cause others like Piwik pro to give errors:
"Broken event
Error message: Tracking parameter `ec_products` has invalid value. Unable to deserialize ecommerce products JSON: invalid type: integer `38625`, expected a string at line 1 column 7"

Can this be fixed?

Thanks!

**Comment by duracelltomi** [comment]
Hi,

This is more about how [wp_json_encode](https://developer.wordpress.org/reference/functions/wp_json_encode/) (calling [json_encode](https://www.php.net/manual/en/function.json-encode.php)) converts a PHP variable into a JSON string.

If it sees a number, it will be encoded as a number, not as a string.
What you could you is to create a custom JS variable inside GTM and iterate through the items array and convert all item_id value to string if necessary.

**Comment by StSaens** [comment]
Hi, thanks for your response.
I dont fully understand, since it's a change from 1.19.1 to 1.20

![v1 19 1](https://github.com/duracelltomi/gtm4wp/assets/11319160/82b4562e-cdbb-45c7-9e45-4159df44299a)
![v1 20](https://github.com/duracelltomi/gtm4wp/assets/11319160/c51d7fa6-7184-4083-8f42-758d3cad1b41)

**Comment by duracelltomi** [comment]
Well, that is strange...

**Comment by duracelltomi** [comment]
Oh, I see, there was another ticket about this. They asked me to make sure the item_id is an integer when it is an integer and not a string :-)

So, who is right now? ;-)

**Comment by StSaens** [comment]
The standard.

**Comment by duracelltomi** [comment]
Deal :-)

**Comment by StSaens** [comment]
Great! 
Is there an issue id with the other request you're referring to? I am interested in their use-case.
