### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'scrollTop')

### ISSUE THREAD

**Issue by krishaamer** [duracelltomi/gtm4wp#326]
Getting this error in the logged-out Chrome console:

```
Uncaught TypeError: Cannot read properties of null (reading 'scrollTop')
    at n (analytics-talk-content-tracking.js?ver=1.20:1:593)
```

```
t >= document.querySelector("#" + gtm4wp_scrollerscript_contentelementid).scrollTop + document.querySelector("#" + gtm4wp_scrollerscript_contentelementid).clientHeight && !c && (e = (new Date).getTime(),
        e = Math.round((e - n) / 1e3),
```

**Comment by duracelltomi** [comment]
This error message indicates that you have entered a wrong content element ID in GTM4WP plugin options.
Can you post the domain name of your site and what you have entered into the content element ID option in GTM4WP?

**Comment by duracelltomi** [comment]
I think this will fix your issue: https://github.com/duracelltomi/gtm4wp/commit/6ed1bd12bf235132c93c5df27f4ec9b15e790c5d
