### ISSUE TITLE
WooCommerce inline JavaScript codes could be moved into a separate .js file

### ISSUE THREAD

**Issue by duracelltomi** [duracelltomi/gtm4wp#34]
Most event handlers are currently added as inline JavaScript codes into the WordPress site. This makes the size of the loaded page larger and can prevent certain cache plugins to fully boost performance on pages.

The plugin could change the behavior of attaching event handlers using jQuery selectors by creating a separate .js file where most event handlers could be defined as functions and WooCommerce/WordPress hooks could be used to add click events directly to the buttons and links.

This would also make the WooCommerce integration more compatible with themes where the standard WooCommerce HTML coding has been abandoned.

**Comment by koconder** [comment]
@duracelltomi build scripts could be added using Grunt.js to minify JS and check for JS issues before build using Travis CI, also some bugs with the current setup in JS.

**Comment by duracelltomi** [comment]
Since this is a huge change, it would be great if many people could try it on test sites

**Comment by ahmed-sigmalux** [comment]
Do you have a beta I can test?

**Comment by duracelltomi** [comment]
Not at this time, but you can use the green "Clone and download" button on this page to download the latest build: https://github.com/duracelltomi/gtm4wp

**Comment by koconder** [comment]
@duracelltomi seems to have bugs, i am seeing JS output in the body HTML of the page tested on https://us.ayanajewellery.com/ - You can see screenshot here: https://imgur.com/a/VxZIuxw

I would suggest rollback on master branch, and using a development branch for the Woocommerce changes. As i had some PR's planned, master branch is now polluted. Thanks

**Comment by duracelltomi** [comment]
I've found the reason for this:
https://www.awesomescreenshot.com/image/3440888/4368fac728bb726fff45bcd6402259ee

A wrong cdata closing tag.
Fixing....

**Comment by ahmed-sigmalux** [comment]
@duracelltomi : Do you have an ETA on the JavaScript improvements? Google is going to start penalizing slow mobile sites in July and the plugin's inline JavaScript is preventing us from deferring jQuery (render blocking script).

**Comment by koconder** [comment]
@duracelltomi still spitting out JS. I had to refactor the "addglobalvars" for WC to utilise add_filter instead of do_action so its wrapped into the script tag. Will push a PR now for the fix. Will also test WC functionality.

**Comment by duracelltomi** [comment]
@ahmed-sigmalux I was on vacation this week with limited access, I will check how this could be done as quickly as possible. Maybe I will reorder planned improvements so that this can go live shortly.
