### ISSUE TITLE
FacebookPixel template not working

### ISSUE THREAD

**Issue by FlexxAlex** [duracelltomi/gtm4wp#344]
Hi, 
I'm trying to implement this template: 
[https://github.com/jabjabonlinemarketing/FacebookPixel-by-JabJab/tree/main](https://github.com/jabjabonlinemarketing/FacebookPixel-by-JabJab/tree/main?fbclid=IwAR3fvmNmFUNan__LMSCQbOklPlhFBbj3LiuNOhr8qwq0Be7QmsSscagUmkk_aem_AWtMqTceK3y07nYxamEfhqbktthIBP6Ok7yNd3JPP0i22QNsaBIkHJFXHjITL6PwFkAaYdOmDWQrDSTRb5gsocTI)
But it keeps giving me an error. 'Import failed because of wrong template format'

The one from Simo works, but I'm trying to implement yours because of the datalayer parameters.

**Comment by FlexxAlex** [comment]
First off, I'm not skilled with coding.
If I put in the .tpl it gives me an error:

1 Error(s) parsing the input:
missing ';' at 'By'
Offending token '' at 3,0.

I solved this by inputting '//' before written text
Then it gives me:

1 Error(s) parsing the input:
missing ']' at ','
Offending token '' at 56,3.

If I do what it expects, I keep getting errors down the road.
I'm obliviously missing something.

**Comment by duracelltomi** [comment]
I am not sure I can see the reason based on those error messages.
I recorded a little video that might help to see the difference between how I install the template and how do you the same:

https://vimeo.com/937742476/1ae897ba07?share=copy

**Comment by FlexxAlex** [comment]
Thanks now it worked!
