### ISSUE TITLE
Choosing to trigger the “purchase” event when you click on the PURCHASE button or on the Thank You Page.

### ISSUE THREAD

**Issue by Tom-nn** [duracelltomi/gtm4wp#370]
Is it possible to implement a choice of triggering the “purchase” event after clicking the PURCHASE button, just before redirecting to the payment gateway, or to the Thank You Page? Currently it is only on the Thank You Page, and in my case it would make more sense to implement it to trigger when the purchase button is clicked.

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by duracelltomi** [comment]
This is not possible as clicking on the purchase button does not create the order on the backend thus essential attributes (transacion ID, revenue) can not be set for tracking.
