### ISSUE TITLE
order_received Is there order_received event?

### ISSUE THREAD

**Issue by alexlii1971** [duracelltomi/gtm4wp#374]
Hello,

I noted there is order_received event in GA4 that can be importing as conversion Goal.

<img width="856" alt="Screen Shot 2024-10-30 at 01 02 08" src="https://github.com/user-attachments/assets/d72dfe7f-7495-4cee-bf3f-520f66399f43">

However, there is no order_received in the trigger of Event - Ecommerce Events:

view_item|view_item_list|select_item|add_to_cart|remove_from_cart|view_cart|begin_checkout|add_payment_info|add_shipping_info|purchase

Also, I noted there is coverage issue:

<img width="1512" alt="Screen Shot 2024-10-30 at 01 00 09" src="https://github.com/user-attachments/assets/a9197cf3-694f-47b3-9259-70e66f14aaf8">

Any suggestions upon set order_received as Enhanced Conversion Goal in this case?

Thanks

**Comment by alexlii1971** [comment]
Just note that there are two method for enhanced conversion:


```
In a separate tab, open Google Tag Manager.

You can set up manual enhanced conversions in 2 different ways for two situations:

Standard manual enhanced conversions: Use this method when user-provided data (email, phone number, or address) is available on the conversion event page. For example, if your conversion event page is the purchase confirmation page and user email is visible on that page, use this method.

Manual enhanced conversions with the user-provided data event tag: Use this method when user-provided data (email, phone number, or address) isn't available on the conversion event page, but is available on a previous page. For example, if your conversion event page is the purchase confirmation page and user email is entered on a page prior to the purchase confirmation page, use this method. In this method, you’ll identify CSS selectors and Javascript variables that contain user-provided data on pages that come before the conversion page.

```
At https://support.google.com/google-ads/answer/13262500?hl=en&sjid=723303542576422197-NC#zippy=%2Cset-up-standard-automatic-enhanced-conversions%2Cset-up-automatic-enhanced-conversions-with-the-user-provided-data-event-tag%2Cenable-enhanced-conversions-in-google-tag-manager

and there are two types:

**Google Ads conversion tracking tag
Google Ads User-Provided Data Event**

It seems that order-received page should be the type of "Google Ads User-Provided Data Event" . Since there is 
 no email address on Woocommerce order-recieved page.

Am I right please?

**Comment by duracelltomi** [comment]
There is not order_received event in GTM4WP.
Someone might have created a custom event in GA4 admin that probably sends this event when the user visits the order reveived page: https://support.google.com/analytics/answer/12844695?hl=en

Tag coverage in GTM is.... well crap... we see lots of false positives in those reports.
To setup Enhanced Conversions, please refer to this article: https://gtm4wp.com/google-tag-manager-for-woocommerce/enhanced-conversions-for-google-ads-with-woocommerce-how-to-setup
