### ISSUE TITLE
Version 1 for Data Layer in ecommerce Variable?

### ISSUE THREAD

**Issue by alexlii1971** [duracelltomi/gtm4wp#375]
Hello,

For the imported Variables, most of them are with version 2.

However, one is version 1, is that expected please?
<img width="885" alt="Screen Shot 2024-10-30 at 01 15 00" src="https://github.com/user-attachments/assets/0e9e1295-315e-4380-b4bc-c550c7c0b979">

Thanks

**Comment by duracelltomi** [comment]
Yes, this is expected, in specific cases this prevents recursive merge to happen. For example with an add_to_cart event you do not want to process the product data pushed into the ecommerce data layer earlier during a view_item_list event on the same page.
