### ISSUE TITLE
wp 6.7.0 problem

### ISSUE THREAD

**Issue by AlkoKod** [duracelltomi/gtm4wp#376]
Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the duracelltomi-google-tag-manager domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. (This message was added in version 6.7.0.)

**Comment by duracelltomi** [comment]
Thanks, I will look into this at least on Monday

**Comment by duracelltomi** [comment]
Fixed: https://github.com/duracelltomi/gtm4wp/commit/c364c1b90ccf41d5438682e9585ee9653670a6e3

**Comment by phpMagpie** [comment]
@duracelltomi thanks for fixing this .. when are you planning on releasing an update so this fix can be applied via plugin updates?
