### ISSUE TITLE
Incorrectly calling _load_textdomain_just_in_time

### ISSUE THREAD

**Issue by Dekadinious** [duracelltomi/gtm4wp#379]
`[20-Nov-2024 14:18:40 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>duracelltomi-google-tag-manager</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /www/any/wp-includes/functions.php on line 6114
`

**Comment by duracelltomi** [comment]
This has been fixed and will be released next Monday. Thanks for flagging it.
