### ISSUE TITLE
AMP – CloudFlare.com – AMPforWP.com

### ISSUE THREAD

**Issue by oG14108149527Exl0Ftr7sY** [duracelltomi/gtm4wp#38]
Please see attached ZIP file.

This is regarding AMP – CloudFlare.com – AMPforWP.com

More info at:
**GIThub**
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/958

**WordPress support AMPforWP.com**
https://wordpress.org/support/topic/gtm-google-tag-manager-error-http-response-code-indicates-tag-failed-to-fire-s/

Trying to make Google Tag Manager work correctly with CloudFlare and AMPforWP.com using "DuracellTomi's Google Tag Manager for WordPress"

**Ref: WordPress support DuracellTomi's**
https://wordpress.org/support/topic/setting-gtm-for-amp-pages/

Attached is a PHP file / WordPress plugin that will place the GTM - Google Tag Manager - code in the correct place in AMPforWP.com

Hope this will make it easier to develp DuracellTomi's Google Tag Manager for WordPress to support AMP through AMPforWP.com

[amp-gtm-plugin.php.zip](https://github.com/duracelltomi/gtm4wp/files/1244085/amp-gtm-plugin.php.zip)

**Comment by oG14108149527Exl0Ftr7sY** [comment]
Hello Thomas

Thank you very much for your help.

The issue is now solved.

Created a separate AMP container and tag.

Now using “AMP” as the container type instead of “Web”.

Everything works correctly.

Thanks

TBT

**Comment by ahmedkaludi** [comment]
@oG14108149527Exl0Ftr7sY Can you explain me what worked?

Please help me so that I can understand and improve the code in the AMP for WP plugin.

**Comment by oG14108149527Exl0Ftr7sY** [comment]
When creating the Google Tag Manager container at:
https://tagmanager.google.com

Then you should create separate containers for the standard WordPress site and the the AMPforWP.com site.

When creating the AMPforWP.com container then you must choose container type= "AMP" 
When creating the container for use with the PC version and standard WordPress theme then you should create a container type= "Web"

This means there will be different "container" / "container type" and different tags for the AMP and the non-AMP version of the site.

**Comment by ahmedkaludi** [comment]
@oG14108149527Exl0Ftr7sY Thanks! We have made changes and also created a tutorial along with a link to with in the GTM section for people who can get the help easily.

Thanks for helping us out with one.

Regards,
Ahmed

**Comment by duracelltomi** [comment]
Thanks for everyone this thread, I am really happy that finally everyone got something new :-)
