### ISSUE TITLE
possible confusion of the code snippet locations in the readme file

### ISSUE THREAD

**Issue by henkisdabro** [duracelltomi/gtm4wp#39]
According to the readme file, it states that "the most important part of the GTM codes" is inside the <head section> and that _this is the iframe part of the code and also that it only fires when javascript is broken/disabled._ This does not sound right: Is this not the other way around:

**head** 
 _- this is the javascript portion without an iframe right?_
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WCRQ6CV');</script>
<!-- End Google Tag Manager -->
```

**body**  
_- clearly this is the iframe part meant for disabled javascript_
```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WCRQ6CV"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by duracelltomi** [comment]
Hi,

Thanks for sharing your comments!
I guess the root of this misunderstanding is that wordpress.org does not escape < and > chars the the readme content making the description confusing.

If you look at the readme.txt itself, it is much better I guess:
https://github.com/duracelltomi/gtm4wp/blob/master/readme.txt#L32

**Comment by henkisdabro** [comment]
the **iframe** part of the GTM snippet is the one that is placed in the **body** section. It is this body-snippet that is used when javascript is disabled.

the **head** section contains the pure javascript portion.

The readme still has this confused in my opinion.

**Comment by duracelltomi** [comment]
So this is the mentioned text:

> GTM container code snippet is currently divided into two parts: **the most important part will be added to the <head> tag** of your website every time. **The second part is called the iframe tag and it is only being used when users do not have JavaScript enabled**. Code placement option only controls this second code snippet. For best performance this should be just after the opening body tag but it might be also safe to use the footer option in plugin settings as the worst case.

Would you be so kind and propose a new text for this paragraph?
