### ISSUE TITLE
UserRegistrationDate is not working

### ISSUE THREAD

**Issue by sensacional** [duracelltomi/gtm4wp#41]
In the last release, user registration date is supposed to appear in the backed. 
It doesn't appear, at least I used the files from the last commit (it indeed has the option in the admin.php file) but somehow it doesn't appear.

![image](https://user-images.githubusercontent.com/21365183/32073824-b75ad8e0-ba6d-11e7-84de-35d9a653fe6e.png)

**Comment by sensacional** [comment]
Update: found it. It was in the Adwords section!

**Comment by duracelltomi** [comment]
I committed a fix for that, would you be so kind and give it a try?
