### ISSUE TITLE
Add ability to push username to the dataLayer

### ISSUE THREAD

**Issue by hellotimtom** [duracelltomi/gtm4wp#46]
I would like to be able to push the WP username to the dataLayer as opposed to the user's email address. Just wondering if possible to include in the future..?
Thanks!

**Comment by duracelltomi** [comment]
This will be included as a new option in plugin settings page
Value will be available in the visitorUsername data layer variable

**Comment by hellotimtom** [comment]
Thanks Thomas, that's great 👍
