### ISSUE TITLE
Outdated notification for plugin version 1.3

### ISSUE THREAD

**Issue by henkisdabro** [duracelltomi/gtm4wp#47]
I ran into this notification just now and realise it could be confusing as the plugin is now version 1.7.x. Perhaps add more insights/details about the notice?

![image](https://user-images.githubusercontent.com/477513/34144010-99a67e12-e4ca-11e7-9dc1-dc37c2fd7a99.png)

**Comment by duracelltomi** [comment]
Thanks for noting!

This message has been already removed from the dev version.
