### ISSUE TITLE
Add an option to track click events on phone numbers

### ISSUE THREAD

**Issue by hellotimtom** [duracelltomi/gtm4wp#48]
Hi there... just a thought to add an option to enable click events of phone numbers (based on href tel) as an addition to the click tracking on email addresses.

Thanks!

**Comment by duracelltomi** [comment]
This does not need an addition to this plugin.

You can create a new trigger on the GTM UI and set it to fire on Link Clicks, then limit the trigger to fire on the following rule: Page URL starts with "tel:"
