### ISSUE TITLE
Affiliation Property Breaks Analytics and Adwords Reports

### ISSUE THREAD

**Issue by zizzfizzix** [duracelltomi/gtm4wp#50]
Hi @duracelltomi 

there's an issue that's well described in https://github.com/magento/magento2/issues/10857 that affects this plugin too. Please let me know if I can be of any more help with resolving this.

The code is found around here:
https://github.com/duracelltomi/gtm4wp/blob/18793b356d3238e865aba979d9d7cfb3f515511a/integration/woocommerce.php#L380

**Comment by duracelltomi** [comment]
Hi,

I have access to lots of WooCommerce shops with my plugin active but I can not see this kind of behavior. Do you experience this issue yourself?

**Comment by zizzfizzix** [comment]
I do, and it took me quite a while to find out what's wrong. Do you need any more info on this?

**Comment by duracelltomi** [comment]
Is it possible to see more details about it?
If you can contact me on my website and grant me read only access to your GA, I could see this in your account.

**Comment by duracelltomi** [comment]
(I just double checked in a GA account of a WooCommerce shop: the source/medium report does not mention any affiliate source or medium, the Channels reports does not show any traffic from "Affiliation" channel - I have the feeling that this issue is related to something else. I would like to help you but I will need to see your reports)

**Comment by zizzfizzix** [comment]
@duracelltomi I have a feeling you're not looking at the same report. I can't give you access as of right now as this is a client's account, but please take a look at the attached screenshot and maybe check again on one of your accounts?
<img width="1364" alt="screen shot 2018-01-21 at 12 13 25" src="https://user-images.githubusercontent.com/652460/35193593-1d3bf81c-fea5-11e7-8ade-ba5e9d1f94cb.png">
All of the orders are filed as affiliate as it overrides everything else (as mentioned in the linked issue).

**Comment by duracelltomi** [comment]
Thanks, that helps!

Just to make sure I understand this clearly:
The only place where you see this kind of misattribution is the overview riport?

**Comment by zizzfizzix** [comment]
Unfortunately I lack sufficient data to be sure, but I figure it's broken in every ecommerce report where you should see eg. Adwords attribution.
