### ISSUE TITLE
Opt in / Opt out for user

### ISSUE THREAD

**Issue by thomasstr** [duracelltomi/gtm4wp#51]
Now that GDPR takes place 25th of May, It should be able for the user to Opt in and Opt out of tracking via the plugin.

**Comment by duracelltomi** [comment]
This is not an issue around the plugin or GTM.

Google Tag Manager itself does not track or store anything, users should give consent about specific tracking like Google Analytics. You may want to store a cookie if user has granted this consent and setup your GTM tags to only fire if this consent is given (=the cookie is set).
