### ISSUE TITLE
Function to return tag ID

### ISSUE THREAD

**Issue by ahmed-sigmalux** [duracelltomi/gtm4wp#54]
Is there a function to return the Google Tag Manager ID? I need to use the ID in another plugin and I'd like to use a built-in function if available.

**Comment by duracelltomi** [comment]
Hi,

For support request, please use the support forum on WordPress.org:
https://wordpress.org/support/plugin/duracelltomi-google-tag-manager

To answer you question: you can use the global variable $gtm4wp_options and read the key gtm-code
This could however include a comma separated list if you have entered multiple container IDs on the admin page.

**Comment by ahmed-sigmalux** [comment]
I looked through the source code and put this together:

```
function my_get_google_tag_manager_id() {
  global $gtm4wp_options;
  if( $gtm4wp_options[ GTM4WP_OPTION_GTM_CODE ] != "" ) {
    $gtm_ids = explode( ",", str_replace( array(";"," "), array(",",""), $gtm4wp_options[ GTM4WP_OPTION_GTM_CODE ] ) );
    foreach( $gtm_ids as $gtm_id ) {
      $gtm_output .= $gtm_id;
    }
  return $gtm_output;
  }
}
```

**Comment by duracelltomi** [comment]
Yes, that will work!
