### ISSUE TITLE
Include IP address in the data layer

### ISSUE THREAD

**Issue by duracelltomi** [duracelltomi/gtm4wp#60]
With GDPR it might be not possible to send full IP address into GA
This means that users will need to filter internal traffic inside GTM.

To be able to do so, the IP address has to be added into the dataLayer

**Comment by tijevlam** [comment]
Hi Tamás,

The IP should, ideally, be added to the dataLayer before GTM itself is loaded to ensure the IP is available from the pageview event and further.

**Comment by duracelltomi** [comment]
This is my intention: there is an initial dataLayer declaration before the GTM container snippet is being added. The plan is to add the IP address here.

**Comment by tijevlam** [comment]
I took the liberty to do a [pull request](https://github.com/duracelltomi/gtm4wp/pull/65). I can see Travis CI failed, but am not sure why, cant see the specifics.

**Comment by koconder** [comment]
@tijevlam travis CI was not working, i have resolved travis ci through another PR just pushed through. The travis CI took quite a while to fix as i had to fix other git repos to get it working.

In regards to #65 PR, might suggest adding a warning/notice around PII

**Comment by tijevlam** [comment]
@koconder thanks for letting me know.

In regard to you comment on #65 PR, I added more explanation on the admin side of things. Did you have something like this in mind? Or would you want it in a different form and or place?

**Comment by koconder** [comment]
@tijevlam looks good, I don't have permission to approve PR, will await @duracelltomi to approve

**Comment by tijevlam** [comment]
@koconder could you tell me how I good force Travis to recheck my PR? Would be great to see if it gets greenlit after your updates.

@duracelltomi, im curious about your opinion on #65 ... would be great if we could merge it these days... just in time before GDPR gets active 😄

**Comment by koconder** [comment]
@tijevlam the travis CI build will fail for now as the Travis CI was recently merged before your PR. Once the PR's are cleared we should see the Build passing.

**Comment by duracelltomi** [comment]
@tijevlam may I propose to name the variable in the data layer as visitorIP instead of remoteIP? This could be better to understand as there are already some visitor prefixed variables and this would be just one additional variable next to the existing visitor variables.

Also I would move this option to the Basic data -> Visitors tab.

This would also need to update the content of js/admin-subtabs.js

For description text I would propose this one:

> Check this option to include the IP address of the visitor. You might use this to filter internal traffic inside your GTM container. Please be aware that per GDPR its not allowed to transmit this full IP address to Google Analytics or to any other measurement system without explicit consent from the visitor.

Any further explanation could be added into a more detailed article on gtm4wp.com

**Comment by duracelltomi** [comment]
This has been added to v1.8.1 which I have just released
