### ISSUE TITLE
[Build] TravisCI Tests Failing

### ISSUE THREAD

**Issue by koconder** [duracelltomi/gtm4wp#64]
A number of the automated Travis CI tests are failing, could help with speeding up developing from detection of bugs for specific PHP/Wordpress versions. Keeping open as an issue, happy to investigate and look into it.

**Comment by duracelltomi** [comment]
Yeah, I was playing around with Travis CI but I have to admin this is a bit beyond my knowledge :-)
I was thinking of removing this now from my Github repo but if you can help me with proper configuration that would be much appreciated :-)

**Comment by koconder** [comment]
@duracelltomi once PR is merged, ill update README.md to show links to code coverage, build and PHP/Wordpress test results.

**Comment by koconder** [comment]
Example of CI data and coverage from my fork: https://scrutinizer-ci.com/g/koconder/gtm4wp/issues/master

**Comment by koconder** [comment]
Will close issue once PR is merged
