### ISSUE TITLE
[Build] Grunt and JavaScript Optimisations

### ISSUE THREAD

**Issue by koconder** [duracelltomi/gtm4wp#68]
Based on #34 and https://wordpress.org/support/topic/minify-code-using-grunt/ - Resolving javascript related issues and dependencies as well as speed optimisation.

- [x] Ensure all JS is decoupled into seperate JS files such as WooCommerce
- [ ] Adding JavaScript Code checking to Travis CI builds
- [ ] Building Grunt tasks to build minified JS for Wordpress
- [ ] Adding and testing with common caching plugins like W3TC and WPRocket, adding changes as required

**Comment by koconder** [comment]
@duracelltomi would be best to work on it once we have a clean-up on the JS side, de-couple all the JS code completely and i can build out PR on a seperate branch to clean-up, optimise and test JS.

**Comment by duracelltomi** [comment]
Let's do this for the next version, after finishing the currently open PRs, I would say this should be done next. I will first start with woocommerce.php as most of the inline codes are here

**Comment by koconder** [comment]
Sounds good, might need to setup a seperate branch once master branch is clean

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by duracelltomi** [comment]
@koconder do you have any idea why this change breaks on PHP7.1?

https://github.com/duracelltomi/gtm4wp/commit/c5951811a210d4b768b9fdaf1331d15205592e26
https://travis-ci.org/duracelltomi/gtm4wp/jobs/385543090

**Comment by koconder** [comment]
@duracelltomi i have a few ideas, issues seem to be with the ruby based tests not passing on PHP7.1 . I can update once my other PR is closed so i can rebase my fork and start fresh on any changes.

**Comment by duracelltomi** [comment]
The travis.yml referenced your fork of wordpress-test-template
I've changed this to my own fork and the build process finished successfully.

**Comment by duracelltomi** [comment]
@koconder do you plan to contribute with this enhancement to v1.10?

**Comment by koconder** [comment]
@duracelltomi apologies i have been on leave. Probably be more like a v1.10 release. We would also need to "build" scripts that pushes commits, so would need to move to a master, dev branch. So i'll have to do some testing on which setup is the easiest, most supported and the best for testing and compressing all the JS files.

Also are you open to having a single compressed JS regardless of what options are enabled, do we want to remove anything that is no longer used/supporteD?

**Comment by duracelltomi** [comment]
@koconder I had also lots of other work

I would like to release v1.10 soon as there are some important fixes and easy additions that needs to be released quickly, perhaps we could work on this in a later version

**Comment by koconder** [comment]
@duracelltomi i've pushed a few new PR's, ill work off milestones where possible to help focus on the key issues first.
