### ISSUE TITLE
Instant Articles support

### ISSUE THREAD

**Issue by robbiet480** [duracelltomi/gtm4wp#72]
Not really an issue, just a heads up that once #70 and #71 are merged (#69 was already merged, thx!), [this PR](https://github.com/Automattic/facebook-instant-articles-wp/pull/941) I just opened on the Instant Articles plugin repo can be safely merged and GTM4WP will have Instant Articles compatibility! In addition to simply adding the code, the IA integration will add a new dataLayer variable `instantArticle` which is `true` if the current page is the transformed Instant Articles view, `false` if otherwise. Adding this variable allows for doing different things based on if you are in a IA view or not. For the moment, I've noted this new variable in the integration name that will show in the IA settings ([screenshot](https://d.pr/i/zoN3KE)) but thought you may want to expose that somewhere in GTM4WP settings or documentation.

Anyway, just wanted to let you know. Love GTM4WP!

**Comment by koconder** [comment]
@robbiet480 great stuff!

Quick one which might be an idea, we could something like `intergration_fbia` `true` this way we can refactor all the other intergations to have the same method. I would then look to extend the main data layer to have another variable called something like `served` which could have the options `fbia` `amp` and for default: `web`

This will allow a quick and easy custom variable for usage on Google Analytics and other plugins and triggers based on how pages were served.

Once the other PR's are merged, im more than happy to look into it.

**Comment by duracelltomi** [comment]
I like the idea of @koconder to have a single variable to show which version of the page was shown.

As for the refactoring: this is planned for v2.0 which will include a better code base and maybe redesign elements of the plugin. Instead of adding ad hoc refactoring, I would like to have this planned first and 'til then I would like to keep the current structure: extending with functions instead of classes.

**Comment by koconder** [comment]
@duracelltomi thanks, we could easily hook into any active "intergrations" within the plugin to build routes. This could also be used as hooks for any other plugins that want to get an idea of the current state.

**Comment by robbiet480** [comment]
@koconder While you're at it, would be good to allow `applenews` too via https://github.com/alleyinteractive/apple-news :).

**Comment by koconder** [comment]
@robbiet480 will move your feature request on Apple News to a new issue, we have some other changes to clean-up first, ill investigate in due-course.
