### ISSUE TITLE
Wrong ecomm_pagetype on search result pages

### ISSUE THREAD

**Issue by duracelltomi** [duracelltomi/gtm4wp#73]
Should be searchresults

**Comment by koconder** [comment]
https://docs.woocommerce.com/document/conditional-tags/ nothing for search results, uses default product archive page on most themes, might work with is_shop() from WC alongside is_search() for WP. Might need to do some tests.

**Comment by duracelltomi** [comment]
Fix is working on my test site:
http://woo.duracelltomi.hu/?s=dddd&post_type=post
http://woo.duracelltomi.hu/?s=dddd&post_type=product
