### ISSUE TITLE
Apple News Support

### ISSUE THREAD

**Issue by koconder** [duracelltomi/gtm4wp#74]
Moving request from https://github.com/duracelltomi/gtm4wp/issues/72 raised by @robbiet480

**Comment by koconder** [comment]
Investigated Apple News Format, tested https://github.com/alleyinteractive/apple-news and cant find any capabilities of triggering HTML, JS or any external analytics pixels within Apple News Format.

Closing ticket as functionality is not possible.

**Comment by robbiet480** [comment]
Durrrrrr my bad @koconder, totally forgot how restrictive Apple is w/ analytics.
