### ISSUE TITLE
HTTP Do Not Track Header

### ISSUE THREAD

**Issue by koconder** [duracelltomi/gtm4wp#76]
Feature/functionality request same as #75 reading the HTTP headers, https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DNT

Functionality can push true/false or 0/1 to variable. Option to disable GA/GTM code from being outputted with DNT Header is present.

May have issues with caching plugins, if so potential to fallback onto JS with:
`navigator.doNotTrack; // "0" or "1"`

**Comment by duracelltomi** [comment]
The variable navigator.doNotTrack can be easily read on the GTM UI and those who would like to honor this setting can adapt their GTM container. I am not sure whether this should be an option on the plugin level.

**Comment by duracelltomi** [comment]
I was thinking about this and since the main goal of the plugin is to support GTM implementations without JavaScript knowledge, I admit that this could be valuable to several users despite that this is easy to read with pure GTM features.
