### ISSUE TITLE
Is visitorEmail plaintext or hashed?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [duracelltomi/gtm4wp#77]
Is the visitorEmail data layer variable plaintext, e.g., me@domain.com, or hashed, .e.g, 2F983FB2B103F108D87FBC30FBAA8332F36EA022A2A0D4147FC0178A9964D50C?

Most (all?) remarketing tags require email addresses to be hashed, usually with SHA256, for privacy and security.

**Comment by duracelltomi** [comment]
The visitorEmail is in plain text in the data layer, some tags require in such form. In case of the need for a hashed email address, this should be done with some custom logic and JS code.

**Comment by ahmed-sigmalux** [comment]
Right, usually the JavaScript version of a tag requires plaintext while the noscript version requires a SHA256 hash.

Thanks for the clarification!
