### ISSUE TITLE
Enhanced ecommerce tracking with variable products JS error

### ISSUE THREAD

**Issue by todeveni** [duracelltomi/gtm4wp#83]
Trying to use enchanced ecommerce tracking and adding a variable product variation to cart triggers javascript error and fails to trigger `gtm4wp.addProductToCartEEC` event.

`Uncaught TypeError: _product_form_variations.forEach is not a function` (line 16 in `js/gtm4wp-woocommerce-enhanced.js`)

I see that the add to cart form has `data-product_variations` attribute as `false`.

The site is only in finnish and swedish. Here's one variable product (Variation: "Harmaa" with "42-43"):
https://www.preston.fi/tuote/medisox-tukisukat-4/

I'm not super familiar with WooCommerce, but managed to find out that [WooCommerce is using some sort of ajax magic](https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/add-to-cart-variation.js) to get variation data, if `product_variations=false`.

What would be the best way to debug this further?

**Comment by duracelltomi** [comment]
I can see the issue on your site but I do not see the solution yet. Maybe a good solution would be to store the selected product variation data during gtm4wp.changeDetailViewEEC and use this while the add to cart event fires
