### ISSUE TITLE
Add an option to prevent flagging WooCommerce orders as being tracked

### ISSUE THREAD

**Issue by duracelltomi** [duracelltomi/gtm4wp#86]
A new checkbox is needed to prevent flagging orders as being tracked as in some cases  (with iDeal in a particular case) the order received page code is executing twice during a single page load which prevents tracking of transactions.

Default behavior should not be changed, the new option should deactivate flagging of orders.

**Comment by nicomollet** [comment]
Thank you, I was about to post an issue regarding those tracking problems.

Any ETA for 1.9?
