### ISSUE TITLE
Send payment method on Purchase event

### ISSUE THREAD

**Issue by svaldesm** [duracelltomi/gtm4wp#89]
This is not an issue or a bug. But seems like people post them here too :)
It would be great to be able to send this. I have several payment methods and some of them (like BACS) have lower "effective" rates, considering that people purchase but doesn't pay later.
Just a suggestion. Thanks!

**Comment by duracelltomi** [comment]
If you enable classic/standard ecommerce, you will have a `transactionPaymentType `item in the data layer. Wouldn't this be enough?

**Comment by svaldesm** [comment]
Hi Thomas, but will that disable enhanced ecommerce )and all the benefits)?

This use case may be for a lot of people. We accept bank transfer which is
very common in here but not all the people end up paying. That can help us
estimate way better our sales.

Santiago Valdés M.

**Comment by duracelltomi** [comment]
No, if you enable classic ecommerce in the plugin as well and setup enhanced ecommerce tags based on my setup article, GTM and GA will not use any datalayer item that is related to the classic ecommerce tracking but you will have the payment method on the order received page.

**Comment by duracelltomi** [comment]
This will be added with an extended scope:
https://github.com/duracelltomi/gtm4wp/issues/130
