### ISSUE TITLE
Add user email for Advanced Matching Facebook retargeting

### ISSUE THREAD

**Issue by accetturo** [duracelltomi/gtm4wp#9]
User email doesnt print, I tried to add it but its not working

**Comment by duracelltomi** [comment]
Could you please describe the issue in more detail?

What did you do exactly, what additional code has been added and where?

**Comment by duracelltomi** [comment]
I just realized what you would like to achieve: adding email address of site users is against the terms of service of Google Tag Manager: https://www.google.com/analytics/tag-manager/use-policy/

It does not mean that technically it is not possible but once someone reports this to Google or Google finds this out while some sort of automated pro-active checking process, your GTM container might be shut down.

**Comment by duracelltomi** [comment]
OK, I digg into more details at Google and found out that passing an email address into the dataLayer might be OK unless you do not send this email address to any Google service.

**Comment by duracelltomi** [comment]
This has been added to the source.
https://github.com/duracelltomi/gtm4wp/commit/702e5cdd2c612af1bebc86585968c7ff1bf32626

**Comment by accetturo** [comment]
Thank you!
