### ISSUE TITLE
ecommerce events are not triggered on cart and checkout page

### ISSUE THREAD

**Issue by robert1112** [duracelltomi/gtm4wp#91]
Hi @duracelltomi 

First off, thank you for sharing this awesome and free plugin. It helps a lot. 

I just start picking up GTM and I noticed UA Enhanced Ecommerce WOO event is not loaded on checkout | cart page. None of the ecommerce trigger show up on debug mode on those page. Here is the trigger. Where should I check?  Thanks so much.

![image](https://user-images.githubusercontent.com/23134805/44547556-18ca5100-a74e-11e8-8147-830efdfdfc43.png)

**Comment by duracelltomi** [comment]
Hi @robert1112 ,

May I ask you why you have added $ after event names? ($ = end of text)
All EEC event names end with EEC (gtm4wp.addProcuctToCartEEC) thus your trigger will not fire at all.

**Comment by robert1112** [comment]
Hi @duracelltomi  

Thanks for your prompt reply.  The reason is `gtm4wp.addProcuctToCartEEC` and `gtm4wp.addProcuctToCart` will have `Facebook Add To Cart`  fire 2 times. 

Will it cause problem? Thank you.

**Comment by duracelltomi** [comment]
Normally that should not happen.

Can you post the domain of your site?

**Comment by robert1112** [comment]
Hi  @duracelltomi  Sorry for my late reply. It was 4 am at my local time. 

My domain is [here](https://dreambox.tw) and I import all the trigger and variables from [this container](
https://github.com/zjuul/gtm4wp_container)

Thank you so much.

**Comment by duracelltomi** [comment]
You seem to have enabled both classic and enhanced ecommerce in plugin options. This is needed in only very rare cases. Having enabled both, you will get similar GTM events for add to cart actions which could cause firing your tag twice.

Please also review my setup instructions for enhanced ecommerce:
https://gtm4wp.com/how-to-articles/how-to-setup-enhanced-ecommerce-tracking

**Comment by robert1112** [comment]
Hi @duracelltomi 

I saw those 2 are both recommended to enable so I just go ahead. 😄 Thanks for the link.

There are are few ecommerce events are not triggered.

- *gtm4wp.productClickEEC*: trigger when  i click any product on category page?
- *gtm4wp.checkoutOptionECC* : trigger when go to checkout page?
- No ecommece event for cart page? 
- Also, when i change shipping mehotd on checkout page, I got this *gtm4wp.checkoutStepEEC* event and wont show up when change shipping method on cart page .

Please kindly advice. THANK YOU VERY MUCH.

**Comment by robert1112** [comment]
- What is the benefit of *gtm4wp.changeDetailViewEEC* ? I noticed it trigger ecommerce tag when i click a product or change color / size variation, right? Thank you.

**Comment by robert1112** [comment]
Hi @duracelltomi  Thank you for your advice. Do I need to add `additional dimension in GA`for all the metrics provided by your plugin?  Thank you again.

**Comment by duracelltomi** [comment]
No, my plugin adds standard enhanced ecommerce dimensions and metrics, you only need to add custom dimensions if you would like to track Google Ads dynamic remarketing based on GA data:
https://support.google.com/analytics/answer/3455585?hl=en

**Comment by robert1112** [comment]
@duracelltomi  Thanks so much for your support and patience, oh and the awesome plugin. 👍
