### ISSUE TITLE
Do I need to add "gtm4wp_the_gtm_tag" script?

### ISSUE THREAD

**Issue by robert1112** [duracelltomi/gtm4wp#92]
If if choose `Custom (needs tweak in your template)` and place these 2 scripts as instructed. 
`Additionally, paste this code immediately after the opening <body> tag:`
`Paste this code as high in the <head> of the page as possible:`

Do I still need to add `<?php if ( function_exists( 'gtm4wp_the_gtm_tag' ) ) { gtm4wp_the_gtm_tag(); } ?>` ? 

It is a bit confusing to me. Please kindly help confirm. Thank you so much.

**Comment by duracelltomi** [comment]
With Custom placement option you need to place this one line of PHP code into your theme's header.php file just after the opening body tag.

**Comment by robert1112** [comment]
Thank you. @duracelltomi
