### ISSUE TITLE
Remove shipping from revenue as well?

### ISSUE THREAD

**Issue by duracelltomi** [duracelltomi/gtm4wp#97]
The new option in v1.9 should also remove the shipping price?
Might need to do some polls first

**Comment by duracelltomi** [comment]
The question was raised via email from some users, I have to admit that the term "revenue" could need some clarification to decide this question.

Within Google Analytics the term "revenue" for ecommerce tracking includes taxes and shipping costs which is the correct definition. "Revenue" is usually the top line, the first important number before expenses are deducted.

But I always thought that this is a bit misleading since in many cases merchants do not intend to measure the income but rather the profit or what is closest to this term. This is why usually it has more value to see in Google Analytics and in other tools the pure order value next to your costs.

What do you think?

**Comment by robert1112** [comment]
Hi @duracelltomi  

Thanks for your reply. I am more like a merchant than a developer. As a shop owner, I would prefer knowing revenue and the breakdown, including shipping fee, tax, and cost. Not sure if it is possible with your plugin and GA?

After removing shipping from revenue, will it create confusion and insistence? Just my two cents. 

Thanks for all the hard work!

**Comment by duracelltomi** [comment]
Currently the default behavior is to send shipping cost and taxes in the revenue amount included.

A new option was introduced in v1.9 which allows you to deduct taxes from this revenue. Question is whether this should also deduct shipping costs?
(without enabling this option, revenue will continue to include taxes and shipping cost)

**Comment by robert1112** [comment]
I prefer not to exclude shipping fee from revenue.  I can get total shipping fee from WC backend and do simple math. Either way, it is better to clearly clarify this on blog post or plugin.

**Comment by Brendonwbrown** [comment]
I personally think it's important to make sure a user can capture shipping, taxes, discounts and revenue separately if desired. My clients end up being pretty picky when launching a new ecomm site, and tend to request all the numbers.

**Comment by duracelltomi** [comment]
I guess the best option will be here to include checkboxes which will be unset by default and with that, everybody can have their satisfaction in terms of what is being included in the "revenue" field and what is not :-)
