### ISSUE TITLE
gtm4wp.changeDetailViewEEC gets fired sometimes twice during pageload

### ISSUE THREAD

**Issue by duracelltomi** [duracelltomi/gtm4wp#98]
On variable product pages where all attribute has a default selection, gtm4wp.changeDetailViewEEC is firing sometimes twice. Reported URL:

https://premiumaudio.nl/producten/yamaha-r-n803d-stereo-receiver/

Not an issue on test site:
http://woo.duracelltomi.hu/product/flying-ninja-coloredn-roll-pre-selected/

**Comment by Blueboots** [comment]
I think I see this same issue. Let me know if any more info from me would be useful to you. I am at the beginning of my Tag Manager journey and often I'm not sure if what I see are bugs or expected behaviour.

**Comment by duracelltomi** [comment]
@Blueboots and help would be appreciated since I can see that this happens on some sites but I can not reproduce on my testing site. Seems for me a theme related issue which we might be able to fix within the code of GTM4WP but not sure how

**Comment by duracelltomi** [comment]
@Blueboots the upcoming v1.10 beta1 now includes a check to prevent this duplicate event issue but I will need someone who could test this.

I will release v1.10 beta1 next Monday, it will be available for download within this repository
